# Generated by Django 4.2.7 on 2023-12-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=255, null=True)),
                ('container_number', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField()),
                ('eta', models.DateField()),
                ('shipping_line', models.CharField(max_length=255)),
                ('container_type', models.CharField(max_length=255)),
                ('departure_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('port_arrived_at', models.DateTimeField(null=True)),
                ('port_picked_at', models.DateTimeField(null=True)),
                ('warehouse_arrived_at', models.DateTimeField(null=True)),
                ('unpacked_at', models.DateTimeField(null=True)),
                ('pickup_method', models.CharField(max_length=255, null=True)),
                ('pickup_id', models.CharField(max_length=255, null=True)),
                ('pickup_scheduled_at', models.DateTimeField(null=True)),
                ('pickup_appointment', models.DateField(null=True)),
                ('palletized_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZemWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('delivery_method', models.CharField(max_length=255)),
                ('shipping_mark', models.CharField(max_length=255, null=True)),
                ('fba_id', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=20, null=True)),
                ('ref_id', models.CharField(max_length=255, null=True)),
                ('pcs', models.IntegerField()),
                ('unit_weight_kg', models.FloatField(null=True)),
                ('total_weight_kg', models.FloatField(null=True)),
                ('unit_weight_lbs', models.FloatField(null=True)),
                ('total_weight_lbs', models.FloatField(null=True)),
                ('cbm', models.FloatField()),
                ('n_pallet', models.IntegerField(null=True)),
                ('container_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.customer'),
        ),
        migrations.AddField(
            model_name='container',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.zemwarehouse'),
        ),
    ]
