# Generated by Django 4.2.7 on 2023-12-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container_id',
            new_name='container_iid',
        ),
        migrations.RenameField(
            model_name='packinglist',
            old_name='container_id',
            new_name='container_iid',
        ),
    ]
