# Generated by Django 4.2.7 on 2023-11-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('eta', models.DateField()),
                ('shipping_line', models.CharField(max_length=255)),
                ('container_type', models.CharField(max_length=255)),
                ('departure_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('warehouse', models.CharField(max_length=255)),
                ('port_arrived_at', models.DateTimeField()),
                ('port_picked_at', models.DateTimeField()),
                ('warehouse_arrived_at', models.DateTimeField()),
                ('unpacked_at', models.DateTimeField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('shipping_mark', models.CharField(max_length=255)),
                ('fba_id', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('ref_id', models.CharField(max_length=255)),
                ('pcs', models.IntegerField()),
                ('unit_weight_kg', models.FloatField()),
                ('total_weight_kg', models.FloatField()),
                ('unit_weight_lbs', models.FloatField()),
                ('total_weight_lbs', models.FloatField()),
                ('cbm', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='departure_port',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination_port',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
