# Generated by Django 4.2.7 on 2023-12-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_container_id_container_container_iid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zemwarehouse',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
