# Generated by Django 4.2.7 on 2023-12-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_packinglist_is_shipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='is_shipment_schduled',
            field=models.BooleanField(default=False),
        ),
    ]
