# Generated by Django 4.2.7 on 2023-11-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_container_id_packinglist_container_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
