# Generated by Django 4.2.7 on 2023-11-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='port_arrived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='port_picked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='unpacked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='warehouse_arrived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='fba_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='ref_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='shipping_mark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
