# Generated by Django 4.2.7 on 2023-11-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_container_port_arrived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.customer'),
        ),
    ]
