# Generated by Django 4.2.7 on 2024-01-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_packinglist_shipment_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_batch_number', models.CharField(max_length=255, null=True)),
                ('carrier', models.CharField(max_length=255, null=True)),
                ('is_shipment_schduled', models.BooleanField(default=False)),
                ('shipment_schduled_at', models.DateTimeField(null=True)),
                ('shipment_appointment', models.DateField(null=True)),
                ('is_shipped', models.BooleanField(default=False)),
                ('shipped_at', models.DateTimeField(null=True)),
                ('is_arrived', models.BooleanField(default=False)),
                ('arrived_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='is_shipment_schduled',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='shipment_appointment',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='shipment_schduled_at',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='shipped_at',
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='shipment_batch_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.shipment'),
        ),
    ]
