# Generated by Django 4.2.7 on 2023-11-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_container_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='total_weight_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='total_weight_lbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='unit_weight_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='unit_weight_lbs',
            field=models.FloatField(null=True),
        ),
    ]
