# Generated by Django 4.2.7 on 2023-12-05 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_packinglist_total_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
