# Generated by Django 4.2.7 on 2024-01-22 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_shipment_remove_packinglist_is_shipment_schduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='shipment_batch_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.shipment'),
        ),
    ]
