# Generated by Django 4.2.7 on 2024-01-28 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_shipment_address_shipment_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_id', models.CharField(max_length=255, null=True)),
                ('clear_by_zem', models.BooleanField(default=True)),
                ('cleared_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offload_id', models.CharField(max_length=255, null=True)),
                ('offload_required', models.BooleanField(default=True)),
                ('offload_at', models.DateTimeField(null=True)),
                ('total_pallet', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_id', models.CharField(max_length=255, null=True)),
                ('retrive_by_zem', models.BooleanField(default=True)),
                ('origin', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('retrieval_location', models.CharField(max_length=255, null=True)),
                ('shipping_line', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('target_retrieval_timestamp', models.DateTimeField(null=True)),
                ('actual_retrieval_timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='zem_name',
        ),
        migrations.RemoveField(
            model_name='container',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='container',
            name='departure_port',
        ),
        migrations.RemoveField(
            model_name='container',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='container',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='container',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='container',
            name='palletized_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='pickup_appointment',
        ),
        migrations.RemoveField(
            model_name='container',
            name='pickup_id',
        ),
        migrations.RemoveField(
            model_name='container',
            name='pickup_method',
        ),
        migrations.RemoveField(
            model_name='container',
            name='pickup_scheduled_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='port_arrived_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='port_picked_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='shipping_line',
        ),
        migrations.RemoveField(
            model_name='container',
            name='unpacked_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='container',
            name='warehouse_arrived_at',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='total_weight_kg',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='unit_weight_kg',
        ),
        migrations.AddField(
            model_name='container',
            name='weight_lbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='cbm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='pcs',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('eta', models.DateTimeField(null=True)),
                ('order_type', models.CharField(max_length=255, null=True)),
                ('clearance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.clearance')),
                ('container_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.container')),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.customer')),
                ('offload_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.offload')),
                ('retrieval_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.retrieval')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.zemwarehouse')),
            ],
        ),
    ]
