# Generated by Django 4.2.7 on 2023-12-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_container_pickup_id_container_pickup_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZEMWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='order_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
