# Generated by Django 4.2.7 on 2024-01-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0010_clearance_is_clearance_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="eta",
            field=models.DateField(null=True),
        ),
    ]
