# Generated by Django 4.2.7 on 2023-12-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_container_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='palletized_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='pickup_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='pickup_scheduled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='n_pallet',
            field=models.IntegerField(null=True),
        ),
    ]
