# Generated by Django 4.2.7 on 2024-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_alter_order_eta"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieval",
            name="shipping_order_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
