# Generated by Django 4.2.7 on 2024-01-31 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0012_retrieval_shipping_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="clearance",
            name="clearance_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.shipment",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="clearance_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.clearance",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="offload_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.offload",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="retrieval_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.retrieval",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_arrived",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_shipment_schduled",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_shipped",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipment_appointment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipment_schduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
