# Generated by Django 4.2.7 on 2024-02-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0016_alter_retrieval_actual_retrieval_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retrieval",
            name="retrieval_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
