# Generated by Django 4.2.7 on 2024-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_pallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='cbm',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='pcs',
        ),
        migrations.AlterField(
            model_name='pallet',
            name='pallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
