# Generated by Django 4.2.7 on 2024-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_packinglist_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
