# Generated by Django 4.2.7 on 2024-04-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_alter_packinglist_address_alter_packinglist_n_pallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='fba_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='shipment_batch_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.shipment'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='shipping_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
