# Generated by Django 4.2.7 on 2024-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_packinglist_total_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='contact_method',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
