# Generated by Django 4.2.7 on 2024-04-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0033_packinglist_contact_method_packinglist_contact_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_id", models.CharField(max_length=255, null=True)),
                ("platform", models.CharField(blank=True, max_length=255, null=True)),
                ("load_type", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateField(null=True)),
                ("pickup_date", models.DateField(null=True)),
                ("zipcode", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight_lbs", models.FloatField(blank=True, null=True)),
                ("cbm", models.FloatField(blank=True, null=True)),
                ("n_pallet", models.IntegerField(blank=True, null=True)),
                ("pcs", models.IntegerField(blank=True, null=True)),
                ("is_lift_gate", models.BooleanField(default=False)),
                ("cost", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "customer_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.customer",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.zemwarehouse",
                    ),
                ),
            ],
        ),
    ]
