# Generated by Django 4.2.7 on 2024-04-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
