# Generated by Django 4.2.7 on 2024-04-17 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_shipment_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='cbm',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='height',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='length',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='n_pallet',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='pcs',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='weight_lbs',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='width',
        ),
        migrations.AddField(
            model_name='packinglist',
            name='quote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_oversize',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='parent_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='is_lift_gate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
