# Generated by Django 4.2.7 on 2024-04-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_alter_quote_is_lift_gate_alter_quote_is_oversize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
