# Generated by Django 4.2.7 on 2024-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0038_quote_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="zem_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
