# Generated by Django 4.2.7 on 2024-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0040_shipment_pod_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retrieval",
            old_name="destination",
            new_name="destination_port",
        ),
        migrations.RenameField(
            model_name="retrieval",
            old_name="origin",
            new_name="origin_port",
        ),
    ]
