# Generated by Django 4.2.7 on 2024-06-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0045_offload_devanning_company_offload_devanning_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accounting_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
