# Generated by Django 4.2.7 on 2024-07-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0046_customer_accounting_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
