# Generated by Django 4.2.7 on 2024-07-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0047_order_invoice_date_order_invoice_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="invoice_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="invoice_link",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.zemwarehouse",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("invoice_date", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "container_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.container",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.invoice",
            ),
        ),
    ]
