# Generated by Django 4.2.7 on 2024-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0048_remove_order_invoice_date_remove_order_invoice_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
