# Generated by Django 4.2.7 on 2024-07-02 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0049_invoice_total_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_statement_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("statement_amount", models.FloatField(blank=True, null=True)),
                ("statement_date", models.DateTimeField(blank=True, null=True)),
                (
                    "statement_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="statement_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.invoicestatement",
            ),
        ),
    ]
