# Generated by Django 4.2.7 on 2024-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0050_invoicestatement_invoice_statement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicestatement",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoicestatement",
            name="statement_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
