# Generated by Django 4.2.7 on 2024-07-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0051_invoicestatement_due_date_alter_invoice_invoice_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicestatement",
            name="invoice_terms",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
