# Generated by Django 4.2.7 on 2024-07-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0052_invoicestatement_invoice_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "warehouse_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cbm", models.FloatField(blank=True, null=True)),
                ("qty", models.FloatField(blank=True, null=True)),
                ("rate", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.invoice",
                    ),
                ),
            ],
        ),
    ]
