# Generated by Django 4.2.7 on 2024-07-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0053_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="received_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
