# Generated by Django 4.2.7 on 2024-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0054_invoice_received_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="note",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
