# Generated by Django 4.2.7 on 2024-07-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0055_invoiceitem_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="distance_mile",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
