# Generated by Django 4.2.7 on 2024-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0056_quote_distance_mile"),
    ]

    operations = [
        migrations.CreateModel(
            name="T49Raw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.CharField(blank=True, max_length=9999, null=True)),
            ],
        ),
    ]
