# Generated by Django 4.2.7 on 2024-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0057_t49raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="t49raw",
            name="header",
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
