# Generated by Django 4.2.7 on 2024-07-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0058_t49raw_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="t49raw",
            name="ip_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
