# Generated by Django 4.2.7 on 2024-07-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0059_t49raw_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="t49raw",
            name="response",
        ),
        migrations.AddField(
            model_name="t49raw",
            name="body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="t49raw",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="t49raw",
            name="header",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
