# Generated by Django 4.2.7 on 2024-07-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0060_remove_t49raw_response_t49raw_body_t49raw_payload_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_id"], name="warehouse_q_quote_i_336eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["parent_id"], name="warehouse_q_parent__f01995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["created_at"], name="warehouse_q_created_ed5093_idx"
            ),
        ),
    ]
