# Generated by Django 4.2.7 on 2024-07-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0062_order_warehouse_o_order_i_0c2a72_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packinglist",
            name="shipment_batch_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packing_list",
                to="warehouse.shipment",
            ),
        ),
    ]
