# Generated by Django 4.2.7 on 2024-07-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0066_alter_packinglist_shipment_batch_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packinglist",
            name="shipment_batch_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packinglist",
                to="warehouse.shipment",
            ),
        ),
    ]
