# Generated by Django 4.2.7 on 2024-07-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0068_alter_order_container_number_alter_order_shipment_id_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["zem_name"], name="warehouse_c_zem_nam_6c982f_idx"
            ),
        ),
    ]
