# Generated by Django 4.2.7 on 2024-07-24 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0069_customer_warehouse_c_zem_nam_6c982f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.invoice",
            ),
        ),
    ]
