# Generated by Django 4.2.7 on 2024-07-31 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0070_alter_order_invoice_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retrieval",
            name="retrieval_location",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_do_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="retrieval_destination_area",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="retrieval_destination_precise",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="vessel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="vessel_eta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="vessel_etd",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="warehouse.zemwarehouse",
            ),
        ),
    ]
