# Generated by Django 4.2.7 on 2024-07-31 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0073_remove_retrieval_vessel_remove_retrieval_vessel_eta_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vessel_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.vessel",
            ),
        ),
    ]
