# Generated by Django 4.2.7 on 2024-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0075_alter_packinglist_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="add_to_t49",
            field=models.BooleanField(default=False),
        ),
    ]
