# Generated by Django 4.2.7 on 2024-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0076_order_add_to_t49"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieval",
            name="temp_t49_available_for_pickup",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="temp_t49_hold_status",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="temp_t49_lfd",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="temp_t49_pod_arrive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="temp_t49_pod_discharge_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
