# Generated by Django 4.2.7 on 2024-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0078_order_packing_list_updloaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieval",
            name="arrive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="arrive_at_destination",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
