# Generated by Django 4.2.7 on 2024-08-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0080_retrieval_empty_returned_retrieval_empty_returned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retrieval",
            name="retrieval_destination_precise",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
