# Generated by Django 4.2.7 on 2024-09-20 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0081_alter_retrieval_retrieval_destination_precise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fleet_number", models.CharField(max_length=255, null=True)),
                ("load_type", models.CharField(blank=True, max_length=255, null=True)),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "third_party_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("departured_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="shipment",
            name="is_full_out",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="fleet_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleet",
                to="warehouse.fleet",
            ),
        ),
    ]
