# Generated by Django 4.2.7 on 2024-09-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0082_fleet_shipment_is_full_out_shipment_fleet_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="pallet_dumpped",
            field=models.FloatField(null=True),
        ),
    ]
