# Generated by Django 4.2.7 on 2024-09-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0082_order_cancel_notification_order_cancel_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fleet_number", models.CharField(max_length=255, null=True)),
                ("origin", models.CharField(blank=True, max_length=255, null=True)),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "third_party_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("departured_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("total_weight", models.FloatField(null=True)),
                ("total_cbm", models.FloatField(null=True)),
                ("total_pallet", models.FloatField(null=True)),
                ("total_pcs", models.FloatField(null=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "multipule_destination",
                    models.BooleanField(blank=True, default=False),
                ),
                ("pod_link", models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="shipment",
            name="is_full_out",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pallet_dumpped",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="fleet_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment",
                to="warehouse.fleet",
            ),
        ),
    ]
