# Generated by Django 4.2.7 on 2024-09-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0083_fleet_shipment_is_full_out_shipment_pallet_dumpped_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="shipped_cbm",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipped_pallet",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipped_pcs",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipped_weight",
            field=models.FloatField(default=0, null=True),
        ),
    ]
