# Generated by Django 4.2.7 on 2024-09-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0084_alter_shipment_pallet_dumpped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="pallet_dumpped",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
