# Generated by Django 4.2.7 on 2024-09-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0084_shipment_shipped_cbm_shipment_shipped_pallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="batch",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="master_batch_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
