# Generated by Django 4.2.7 on 2024-09-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0085_alter_shipment_pallet_dumpped"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="load_type",
        ),
        migrations.AddField(
            model_name="fleet",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
