# Generated by Django 4.2.7 on 2024-09-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0085_shipment_batch_shipment_master_batch_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="master_batch_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
