# Generated by Django 4.2.7 on 2024-09-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0086_alter_shipment_master_batch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="shipped_cbm",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="shipped_pallet",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="shipped_pcs",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="shipped_weight",
            field=models.FloatField(default=0, null=True),
        ),
    ]
