# Generated by Django 4.2.7 on 2024-09-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0086_remove_fleet_load_type_fleet_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="appointment_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="multipule_destination",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
