# Generated by Django 4.2.7 on 2024-09-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0087_fleet_appointment_time_fleet_multipule_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="pod_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="total_cbm",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="total_pallet",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="total_pcs",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="total_weight",
            field=models.FloatField(null=True),
        ),
    ]
