# Generated by Django 4.2.7 on 2024-09-27 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0087_fleet_shipped_cbm_fleet_shipped_pallet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packinglist",
            name="n_pallet",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
