# Generated by Django 4.2.7 on 2024-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0088_fleet_pod_link_fleet_total_cbm_fleet_total_pallet_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="appointment_time",
        ),
        migrations.AddField(
            model_name="fleet",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
