# Generated by Django 4.2.7 on 2024-10-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0088_alter_packinglist_n_pallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="shipment_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallet",
                to="warehouse.shipment",
            ),
        ),
    ]
