# Generated by Django 4.2.7 on 2024-09-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0089_remove_fleet_appointment_time_fleet_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="multipule_destination",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
