# Generated by Django 4.2.7 on 2024-09-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0090_alter_fleet_multipule_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="fleet_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment",
                to="warehouse.fleet",
            ),
        ),
    ]
