# Generated by Django 4.2.7 on 2024-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0091_pallet_container_number_pallet_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="delivery_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
