# Generated by Django 4.2.7 on 2024-10-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0092_pallet_delivery_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbnormalOffloadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pcs_reported", models.IntegerField(blank=True, null=True)),
                ("pcs_actual", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(max_length=1000, null=True)),
                (
                    "container_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offload_status",
                        to="warehouse.container",
                    ),
                ),
                (
                    "offload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offload_status",
                        to="warehouse.offload",
                    ),
                ),
            ],
        ),
    ]
