# Generated by Django 4.2.7 on 2024-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0093_abnormaloffloadstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="deivery_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="abnormaloffloadstatus",
            name="note",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
