# Generated by Django 4.2.7 on 2024-10-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0094_abnormaloffloadstatus_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="note",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
