# Generated by Django 4.2.7 on 2024-10-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0095_pallet_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pallet",
            name="packing_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.packinglist",
            ),
        ),
    ]
