# Generated by Django 4.2.7 on 2024-10-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0096_alter_pallet_packing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormaloffloadstatus',
            name='abnormal_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
