# Generated by Django 4.2.7 on 2024-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0097_abnormaloffloadstatus_abnormal_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="confirmed_by_warehouse",
            field=models.BooleanField(default=False),
        ),
    ]
