# Generated by Django 5.1.1 on 2024-10-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0099_pallet_fba_id_pallet_ref_id_pallet_shipping_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoCheckEtaSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('last_checktime', models.DateTimeField(blank=True, null=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('handling_method', models.CharField(blank=True, max_length=255, null=True)),
                ('container_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.container')),
            ],
        ),
    ]
