# Generated by Django 5.1.1 on 2024-10-25 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0100_pochecketaseven'),
    ]

    operations = [
        migrations.AddField(
            model_name='pochecketaseven',
            name='packing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.packinglist'),
        ),
    ]
