# Generated by Django 4.2.7 on 2024-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0101_pallet_address_pallet_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieval",
            name="assigned_by_appt",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
