# Generated by Django 5.1.1 on 2024-10-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0102_pochecketaseven_destination_pochecketaseven_fba_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pochecketaseven',
            name='packing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.packinglist'),
        ),
    ]
