# Generated by Django 4.2.7 on 2024-10-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0102_retrieval_assigned_by_appt"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="ready_to_ship",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="ready_to_ship",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
