# Generated by Django 4.2.7 on 2024-10-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0103_pallet_ready_to_ship_shipment_ready_to_ship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pallet",
            name="ready_to_ship",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="ready_to_ship",
        ),
        migrations.AddField(
            model_name="pallet",
            name="abnormal_palletization",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="pallet",
            name="po_expired",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="abnormal_palletization",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="po_expired",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
