# Generated by Django 5.1.1 on 2024-10-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0104_pochecketaseven_time_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pochecketaseven',
            name='vessel_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
