# Generated by Django 4.2.7 on 2024-10-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0104_remove_pallet_ready_to_ship_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abnormaloffloadstatus",
            old_name="deivery_method",
            new_name="delivery_method",
        ),
    ]
