# Generated by Django 4.2.7 on 2024-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0105_rename_deivery_method_abnormaloffloadstatus_delivery_method",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="in_use",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
