# Generated by Django 5.1.1 on 2024-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0105_pochecketaseven_vessel_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pochecketaseven',
            old_name='last_checktime',
            new_name='last_eta_checktime',
        ),
        migrations.AddField(
            model_name='pochecketaseven',
            name='last_retrieval_checktime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
