# Generated by Django 5.1.1 on 2024-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0106_rename_last_checktime_pochecketaseven_last_eta_checktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pochecketaseven',
            name='vessel_eta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
