# Generated by Django 4.2.7 on 2024-10-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0106_shipment_in_use_shipment_shipment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="is_canceled",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
