# Generated by Django 5.1.1 on 2024-10-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0107_alter_pochecketaseven_vessel_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pochecketaseven',
            old_name='status',
            new_name='last_eta_status',
        ),
        migrations.AddField(
            model_name='pochecketaseven',
            name='last_retrieval_status',
            field=models.BooleanField(default=False),
        ),
    ]
