# Generated by Django 4.2.7 on 2024-10-28 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0109_fleet_dot_number_fleet_license_plate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="cancelation_reason",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="is_canceled",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="cancelation_reason",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name="ShipmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_batch_number_str",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "related_batch_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "related_third_party",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipment_batch_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FleetShipmentPallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fleet_number_str",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipment_batch_number_str",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pallet_id_str",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fleet_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.fleet",
                    ),
                ),
                (
                    "pallet_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.pallet",
                    ),
                ),
                (
                    "shipment_batch_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.shipment",
                    ),
                ),
            ],
        ),
    ]
