# Generated by Django 4.2.7 on 2024-10-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0110_fleet_cancelation_reason_fleet_is_canceled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="priority",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
