# Generated by Django 4.2.7 on 2024-10-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0111_pallet_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="appointment_date",
        ),
        migrations.AddField(
            model_name="fleet",
            name="appointment_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
