# Generated by Django 4.2.7 on 2024-10-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0112_remove_fleet_appointment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="is_canceled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="multipule_destination",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="abnormal_palletization",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="po_expired",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="abnormal_palletization",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="in_use",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_arrived",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_canceled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_full_out",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_shipped",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="po_expired",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
