# Generated by Django 4.2.7 on 2024-10-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0114_alter_shipment_shipment_batch_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="total_cbm",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_pallet",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_pcs",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_weight",
            field=models.FloatField(default=0, null=True),
        ),
    ]
