# Generated by Django 4.2.7 on 2024-10-30 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0115_alter_shipment_total_cbm_alter_shipment_total_pallet_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PoCheckEtaSeven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vessel_eta", models.DateField(blank=True, null=True)),
                (
                    "shipping_mark",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("fba_id", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ref_id", models.CharField(blank=True, max_length=400, null=True)),
                ("last_eta_status", models.BooleanField(default=False)),
                ("last_retrieval_status", models.BooleanField(default=False)),
                ("last_eta_checktime", models.DateTimeField(blank=True, null=True)),
                (
                    "last_retrieval_checktime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("time_status", models.BooleanField(default=False)),
                ("is_notified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "handling_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "container_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.container",
                    ),
                ),
                (
                    "packing_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.packinglist",
                    ),
                ),
            ],
        ),
    ]
