# Generated by Django 4.2.7 on 2024-10-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0116_pochecketaseven"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="fba_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="ref_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="shipping_mark",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
