# Generated by Django 4.2.7 on 2024-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0118_fleet_fleet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="priority",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
