# Generated by Django 4.2.7 on 2024-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0122_fleet_pod_uploaded_at_shipment_pod_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="status_description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="previous_fleets",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="status_description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
