# Generated by Django 5.1.1 on 2024-11-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0123_fleet_status_fleet_status_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieval",
            name="target_retrieval_timestamp_lower",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
