# Generated by Django 5.1.1 on 2024-12-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0125_shipment_arm_bol_shipment_arm_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ), 
    ]
