# Generated by Django 5.1.1 on 2024-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0125_shipment_arm_bol_shipment_arm_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
