# Generated by Django 5.1.1 on 2024-12-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0126_order_invoice_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_reject_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]

