# Generated by Django 5.1.1 on 2024-12-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0128_order_invoice_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.FloatField(blank=True, null=True)),
                ('chassis', models.FloatField(blank=True, null=True)),
                ('chassis_split', models.FloatField(blank=True, null=True)),
                ('prepull', models.FloatField(blank=True, null=True)),
                ('Yard_storage', models.FloatField(blank=True, null=True)),
                ('handling_fee', models.FloatField(blank=True, null=True)),
                ('pier_pass', models.FloatField(blank=True, null=True)),
                ('congestion_fee', models.FloatField(blank=True, null=True)),
                ('hanging_crane', models.FloatField(blank=True, null=True)),
                ('dry_run', models.FloatField(blank=True, null=True)),
                ('exam_fee', models.FloatField(blank=True, null=True)),
                ('hazmat', models.FloatField(blank=True, null=True)),
                ('over_weight', models.FloatField(blank=True, null=True)),
                ('urgent_fee', models.FloatField(blank=True, null=True)),
                ('other_serive', models.FloatField(blank=True, null=True)),
                ('demurrage', models.FloatField(blank=True, null=True)),
                ('per_diem', models.FloatField(blank=True, null=True)),
                ('second_pickup', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('container_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.container')),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.invoice')),
            ],
        ),
    ]
