# Generated by Django 5.1.1 on 2024-12-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0129_rename_yard_storage_invoicepreport_yard_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('po_activation', models.FloatField(blank=True, null=True)),
                ('self_pickup', models.FloatField(blank=True, null=True)),
                ('re_pallet', models.FloatField(blank=True, null=True)),
                ('handling', models.FloatField(blank=True, null=True)),
                ('counting', models.FloatField(blank=True, null=True)),
                ('warehouse_rent', models.FloatField(blank=True, null=True)),
                ('specified_labeling', models.FloatField(blank=True, null=True)),
                ('inner_outer_box', models.FloatField(blank=True, null=True)),
                ('inner_outer_box_label', models.FloatField(blank=True, null=True)),
                ('pallet_label', models.FloatField(blank=True, null=True)),
                ('open_close_box', models.FloatField(blank=True, null=True)),
                ('destroy', models.FloatField(blank=True, null=True)),
                ('take_photo', models.FloatField(blank=True, null=True)),
                ('take_video', models.FloatField(blank=True, null=True)),
                ('repeated_operation_fee', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.invoice')),
            ],
        ),
    ]

