# Generated by Django 5.1.1 on 2024-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0130_remove_pallet_price_quote_pallet_invoice_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedelivery',
            name='invoice_delivery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
