# Generated by Django 5.1.1 on 2024-12-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0132_rename_amount_invoicedelivery_total_cbm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='delivery_type',
        ),
    ]
