# Generated by Django 5.1.1 on 2024-12-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0134_invoicedelivery_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
