# Generated by Django 5.1.1 on 2024-12-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0134_rename_total_amount_invoice_amazon_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amazon_amount',
            new_name='delivery_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='combine_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='local_amount',
        ),
    ]
