# Generated by Django 5.1.1 on 2024-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0136_pallet_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='sequence_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
