# Generated by Django 4.2.7 on 2025-01-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0139_invoicedelivery_total_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
