# Generated by Django 5.1.1 on 2025-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0140_pallet_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
