# Generated by Django 4.2.7 on 2025-01-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0141_pallet_po_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglist",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
