# Generated by Django 5.1.1 on 2025-01-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0144_fleet_fleet_zem_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='cost_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
