# Generated by Django 4.2.7 on 2025-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0146_fleet_warehouse_f_fleet_n_d6a026_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["appointment_id"], name="warehouse_s_appoint_02a15a_idx"
            ),
        ),
    ]
