# Generated by Django 4.2.7 on 2025-01-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0148_fleet_amf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='amf_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_zem_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
