# Generated by Django 4.2.7 on 2025-01-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0149_alter_fleet_amf_id_alter_fleet_fleet_zem_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="appointment_datetime_tz",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_appointment_tz",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
