# Generated by Django 5.1.1 on 2025-01-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0150_fleet_appointment_datetime_tz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
