# Generated by Django 5.1.1 on 2025-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0153_transferlocation_container_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlocation',
            name='plt_ids',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
