# Generated by Django 4.2.7 on 2025-03-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0154_transferlocation_plt_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
