# Generated by Django 5.1.1 on 2025-03-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0155_invoicepreport_surcharge_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicewarehouse',
            name='surcharge_notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='invoicewarehouse',
            name='surcharges',
            field=models.JSONField(default=dict),
        ),
    ]
