# Generated by Django 4.2.7 on 2025-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0156_invoicewarehouse_surcharge_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedelivery',
            name='surcharge_notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='invoicedelivery',
            name='surcharges',
            field=models.JSONField(default=dict),
        ),
    ]
