# Generated by Django 4.2.7 on 2025-03-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0157_historicalzemwarehouse_historicalvessel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="username",
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
