# Generated by Django 4.2.7 on 2025-03-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0165_quotationmaster_feedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmaster',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
