# Generated by Django 4.2.7 on 2025-03-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0166_quotationmaster_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicedelivery",
            name="surcharge_notes",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalinvoicedelivery",
            name="surcharges",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalinvoicepreport",
            name="surcharge_notes",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalinvoicepreport",
            name="surcharges",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalinvoicewarehouse",
            name="surcharge_notes",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalinvoicewarehouse",
            name="surcharges",
            field=models.JSONField(default=dict),
        ),
    ]
