# Generated by Django 4.2.7 on 2025-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0168_historicalinvoicepreport_other_fees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicewarehouse",
            name="other_fees",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="invoicewarehouse",
            name="other_fees",
            field=models.JSONField(default=dict),
        ),
    ]
