# Generated by Django 4.2.7 on 2025-03-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0170_historicalinvoicedelivery_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="warehouse.invoice",
            ),
        ),
    ]
