# Generated by Django 4.2.7 on 2025-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0171_alter_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicewarehouse',
            name='split_delivery',
            field=models.FloatField(blank=True, null=True, verbose_name='拆柜交付快递'),
        ),
        migrations.AddField(
            model_name='invoicewarehouse',
            name='split_delivery',
            field=models.FloatField(blank=True, null=True, verbose_name='拆柜交付快递'),
        ),
    ]
