# Generated by Django 4.2.7 on 2025-04-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0176_remove_historicalorder_sub_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payable_status',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'invoice_type': 'payable'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.invoicestatus'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='receivable_status',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'invoice_type': 'receivable'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.invoicestatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='payable_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'invoice_type': 'payable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_orders', to='warehouse.invoicestatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='receivable_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'invoice_type': 'receivable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_orders', to='warehouse.invoicestatus'),
        ),
    ]
