# Generated by Django 4.2.7 on 2025-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0178_rename_delivery_amount_historicalinvoice_payable_delivery_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvoicepreport',
            old_name='delivery_type',
            new_name='invoice_type',
        ),
        migrations.RenameField(
            model_name='invoicepreport',
            old_name='delivery_type',
            new_name='invoice_type',
        ),
        migrations.AddField(
            model_name='historicalinvoicedelivery',
            name='invoice_type',
            field=models.CharField(choices=[('receivable', '应收账单'), ('payable', '应付账单')], default='receivable', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoicewarehouse',
            name='invoice_type',
            field=models.CharField(choices=[('receivable', '应收账单'), ('payable', '应付账单')], default='receivable', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicedelivery',
            name='invoice_type',
            field=models.CharField(choices=[('receivable', '应收账单'), ('payable', '应付账单')], default='receivable', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicewarehouse',
            name='invoice_type',
            field=models.CharField(choices=[('receivable', '应收账单'), ('payable', '应付账单')], default='receivable', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalinvoicedelivery',
            name='delivery_type',
            field=models.CharField(choices=[('public', '公仓'), ('other', '其他')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalinvoicewarehouse',
            name='delivery_type',
            field=models.CharField(choices=[('public', '公仓'), ('other', '其他')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicedelivery',
            name='delivery_type',
            field=models.CharField(choices=[('public', '公仓'), ('other', '其他')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicewarehouse',
            name='delivery_type',
            field=models.CharField(choices=[('public', '公仓'), ('other', '其他')], default='public', max_length=20),
        ),
    ]
