# Generated by Django 4.2.7 on 2025-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0180_container_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicedelivery',
            name='po_activation',
            field=models.FloatField(blank=True, null=True, verbose_name='亚马逊PO激活'),
        ),
        migrations.AddField(
            model_name='historicalinvoicedelivery',
            name='qty',
            field=models.JSONField(default=dict, verbose_name='基础单价'),
        ),
        migrations.AddField(
            model_name='historicalinvoicedelivery',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='historicalinvoicepreport',
            name='qty',
            field=models.JSONField(default=dict, verbose_name='基础单价'),
        ),
        migrations.AddField(
            model_name='historicalinvoicepreport',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='historicalinvoicewarehouse',
            name='qty',
            field=models.JSONField(default=dict, verbose_name='基础单价'),
        ),
        migrations.AddField(
            model_name='historicalinvoicewarehouse',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicedelivery',
            name='po_activation',
            field=models.FloatField(blank=True, null=True, verbose_name='亚马逊PO激活'),
        ),
        migrations.AddField(
            model_name='invoicedelivery',
            name='qty',
            field=models.JSONField(default=dict, verbose_name='基础单价'),
        ),
        migrations.AddField(
            model_name='invoicedelivery',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicepreport',
            name='qty',
            field=models.JSONField(default=dict, verbose_name='基础单价'),
        ),
        migrations.AddField(
            model_name='invoicepreport',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicewarehouse',
            name='qty',
            field=models.JSONField(default=dict, verbose_name='基础单价'),
        ),
        migrations.AddField(
            model_name='invoicewarehouse',
            name='rate',
            field=models.JSONField(default=dict, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='stage_other',
            field=models.CharField(choices=[('pending', '待处理'), ('warehouse_completed', '仓库已完成'), ('delivery_completed', '派送已完成'), ('warehouse_rejected', '仓库已驳回'), ('delivery_rejected', '派送已驳回')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='stage_public',
            field=models.CharField(choices=[('pending', '待处理'), ('warehouse_completed', '仓库已完成'), ('delivery_completed', '派送已完成'), ('warehouse_rejected', '仓库已驳回'), ('delivery_rejected', '派送已驳回')], default='pending', max_length=20),
        ),
    ]
