# Generated by Django 4.2.7 on 2025-04-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0182_historicalinvoicedelivery_cost_invoicedelivery_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoicedelivery',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicedelivery',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='invoicedelivery',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='invoicedelivery',
            name='rate',
        ),
    ]
