# Generated by Django 4.2.7 on 2025-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0183_remove_historicalinvoicedelivery_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="qty",
            field=models.JSONField(default=dict, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="rate",
            field=models.JSONField(default=dict, verbose_name="基础单价"),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="qty",
            field=models.JSONField(default=dict, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="rate",
            field=models.JSONField(default=dict, verbose_name="基础单价"),
        ),
    ]
