# Generated by Django 4.2.7 on 2025-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0184_alter_historicalinvoicepreport_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="qty",
            field=models.JSONField(default=dict, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="rate",
            field=models.JSONField(default=dict, verbose_name="基础单价"),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="qty",
            field=models.JSONField(default=dict, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="rate",
            field=models.JSONField(default=dict, verbose_name="基础单价"),
        ),
    ]
