# Generated by Django 4.2.7 on 2025-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0185_alter_historicalinvoicewarehouse_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="other_fees",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="qty",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="数量"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="rate",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="基础单价"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="surcharge_notes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoicepreport",
            name="surcharges",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="other_fees",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="qty",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="数量"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="rate",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="基础单价"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="surcharge_notes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoicewarehouse",
            name="surcharges",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="other_fees",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="qty",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="数量"
            ),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="rate",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="基础单价"
            ),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="surcharge_notes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="invoicepreport",
            name="surcharges",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="other_fees",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="qty",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="数量"
            ),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="rate",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="基础单价"
            ),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="surcharge_notes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="invoicewarehouse",
            name="surcharges",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
