# Generated by Django 4.2.7 on 2025-04-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0188_feedetail_niche_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_invoice_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_invoice_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
