# Generated by Django 4.2.7 on 2025-04-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0189_historicalinvoice_is_invoice_delivered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoicedelivery",
            name="total_pallet",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoicedelivery",
            name="total_pallet",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
