# Generated by Django 4.2.7 on 2025-05-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0192_container_account_order_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="balance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
