# Generated by Django 4.2.7 on 2025-05-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0197_historicalinvoice_remain_offset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationmaster',
            name='active',
        ),
        migrations.AddField(
            model_name='quotationmaster',
            name='quote_type',
            field=models.CharField(choices=[('receivable', '应收'), ('payable', '应付')], default='receivable', max_length=20, verbose_name='报价类型'),
        ),
    ]
