# Generated by Django 4.2.7 on 2025-06-10 02:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "warehouse",
            "0199_rename_payable_delivery_amount_historicalinvoice_payable_basic_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInvoiceStatus",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("receivable", "应收账单"), ("payable", "应付账单")],
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("unstarted", "未录入"),
                            ("preport", "港前"),
                            ("warehouse", "仓库"),
                            ("delivery", "派送"),
                            ("tobeconfirmed", "待确认"),
                            ("confirmed", "已完成"),
                        ],
                        default="unstarted",
                        max_length=20,
                    ),
                ),
                (
                    "stage_public",
                    models.CharField(
                        choices=[
                            ("pending", "仓库待处理"),
                            ("warehouse_completed", "仓库已完成"),
                            ("delivery_completed", "派送已完成"),
                            ("warehouse_rejected", "仓库已驳回"),
                            ("delivery_rejected", "派送已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stage_other",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("warehouse_completed", "仓库已完成"),
                            ("delivery_completed", "派送已完成"),
                            ("warehouse_rejected", "仓库已驳回"),
                            ("delivery_rejected", "派送已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_rejected", models.BooleanField(default=False)),
                ("reject_reason", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "container_number",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehouse.container",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical invoice status",
                "verbose_name_plural": "historical invoice statuss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
