# Generated by Django 4.2.7 on 2025-06-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0200_historicalinvoicestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalshipment",
            name="arrived_at_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="shipment_appointment_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="shipped_at_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="arrived_at_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_appointment_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipped_at_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
