# Generated by Django 4.2.7 on 2025-06-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0200_historicalinvoicestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpallet",
            name="actual_shipment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="warehouse.shipment",
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="actual_shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallet_actual",
                to="warehouse.shipment",
            ),
        ),
    ]
