# Generated by Django 4.2.7 on 2025-06-23 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0201_historicalpallet_actual_shipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpackinglist",
            name="actual_shipment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="warehouse.shipment",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="actual_shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packinglist_actual",
                to="warehouse.shipment",
            ),
        ),
    ]
