# Generated by Django 4.2.7 on 2025-06-24 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0202_historicalpackinglist_actual_shipment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpackinglist",
            old_name="actual_shipment",
            new_name="master_shipment_batch_number",
        ),
        migrations.RenameField(
            model_name="historicalpallet",
            old_name="actual_shipment",
            new_name="master_shipment_batch_number",
        ),
        migrations.RemoveField(
            model_name="packinglist",
            name="actual_shipment",
        ),
        migrations.RemoveField(
            model_name="pallet",
            name="actual_shipment",
        ),
        migrations.AddField(
            model_name="packinglist",
            name="master_shipment_batch_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packinglist_master",
                to="warehouse.shipment",
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="master_shipment_batch_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallet_master",
                to="warehouse.shipment",
            ),
        ),
    ]
