# Generated by Django 4.2.7 on 2025-06-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0201_historicalshipment_arrived_at_utc_and_more"),
        (
            "warehouse",
            "0203_rename_actual_shipment_historicalpackinglist_master_shipment_batch_number_and_more",
        ),
    ]

    operations = []
