# Generated by Django 4.2.7 on 2025-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0205_fleet_pickup_number_historicalfleet_pickup_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="fleet_cost",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="historicalfleet",
            name="fleet_cost",
            field=models.FloatField(null=True),
        ),
    ]
