# Generated by Django 4.2.7 on 2025-07-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0206_fleet_fleet_cost_historicalfleet_fleet_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleetshipmentpallet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fleetshipmentpallet",
            name="fleet_number_str",
        ),
        migrations.RemoveField(
            model_name="fleetshipmentpallet",
            name="pallet_id",
        ),
        migrations.RemoveField(
            model_name="fleetshipmentpallet",
            name="pallet_id_str",
        ),
        migrations.RemoveField(
            model_name="fleetshipmentpallet",
            name="shipment_batch_number_str",
        ),
        migrations.RemoveField(
            model_name="historicalfleetshipmentpallet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalfleetshipmentpallet",
            name="fleet_number_str",
        ),
        migrations.RemoveField(
            model_name="historicalfleetshipmentpallet",
            name="pallet_id",
        ),
        migrations.RemoveField(
            model_name="historicalfleetshipmentpallet",
            name="pallet_id_str",
        ),
        migrations.RemoveField(
            model_name="historicalfleetshipmentpallet",
            name="shipment_batch_number_str",
        ),
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="container_number",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.container",
            ),
        ),
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="pickup_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="total_pallet",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="container_number",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="warehouse.container",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="pickup_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="total_pallet",
            field=models.FloatField(default=0, null=True),
        ),
    ]
