# Generated by Django 4.2.7 on 2025-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0216_remove_historicalinvoicestatus_statuses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpackinglist",
            name="delivery_window_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpackinglist",
            name="delivery_window_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="delivery_window_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="delivery_window_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="delivery_window_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="delivery_window_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pallet",
            name="delivery_window_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pallet",
            name="delivery_window_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
