# Generated by Django 4.2.7 on 2025-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0217_historicalpackinglist_delivery_window_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="delivery_window_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="delivery_window_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalabnormaloffloadstatus",
            name="delivery_window_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalabnormaloffloadstatus",
            name="delivery_window_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
