# Generated by Django 4.2.7 on 2025-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0218_abnormaloffloadstatus_delivery_window_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpallet",
            name="direction",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="slot",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pallet",
            name="direction",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pallet",
            name="slot",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
