# Generated by Django 4.2.7 on 2025-09-12 07:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0222_alter_container_non_combina_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="arrival_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalretrieval",
            name="unpacking_status",
            field=models.BooleanField(blank=True, default=False),
        ),

        migrations.AddField(
            model_name="retrieval",
            name="arrival_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="unpacking_status",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="feedetail",
            name="niche_warehouse",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
