# Generated by Django 4.2.7 on 2025-08-26 08:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0222_alter_container_non_combina_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpackinglist",
            name="express_number",
            field=models.CharField(blank=True, null=True, verbose_name="快递单号"),
        ),
        migrations.AddField(
            model_name="historicalpackinglist",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="高",
            ),
        ),
        migrations.AddField(
            model_name="historicalpackinglist",
            name="long",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="长",
            ),
        ),
        migrations.AddField(
            model_name="historicalpackinglist",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="宽",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="express_number",
            field=models.CharField(blank=True, null=True, verbose_name="快递单号"),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="高",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="long",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="长",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
                verbose_name="宽",
            ),
        ),
    ]