# Generated by Django 4.2.7 on 2025-09-03 07:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0222_alter_container_non_combina_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpallet",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="pallet",
            name="direction",
        ),
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="transfer_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.transferlocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="transfer_number",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="warehouse.transferlocation",
            ),
        ),

        migrations.AddField(
            model_name="historicaltransferlocation",
            name="fleet_number",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="warehouse.fleet",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransferlocation",
            name="note",
            field=models.CharField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name="transferlocation",
            name="fleet_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferlocation",
                to="warehouse.fleet",
            ),
        ),
        migrations.AddField(
            model_name="transferlocation",
            name="note",
            field=models.CharField(blank=True, null=True),
        ),
    ]
