# Generated by Django 4.2.7 on 2025-08-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0223_historicalpackinglist_express_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransferlocation',
            name='fleet_number',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.fleet'),
        ),
        migrations.AddField(
            model_name='transferlocation',
            name='fleet_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferlocation', to='warehouse.fleet'),
        ),
    ]
