# Generated by Django 4.2.7 on 2025-09-13 07:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0223_historicalpackinglist_express_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="warehouse_unpacked_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="仓库确认拆柜完成时间"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="warehouse_unpacking_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="首次下载拆柜单变拆柜中时间"
            ),
        ),

        migrations.AddField(
            model_name="offload",
            name="warehouse_unpacked_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="仓库确认拆柜完成时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="warehouse_unpacking_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="首次下载拆柜单变拆柜中时间"
            ),
        ),

    ]
