# Generated by Django 4.2.7 on 2025-08-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0224_historicaltransferlocation_fleet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetshipmentpallet',
            name='transfer_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.transferlocation'),
        ),
        migrations.AddField(
            model_name='historicalfleetshipmentpallet',
            name='transfer_number',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.transferlocation'),
        ),
    ]
