# Generated by Django 4.2.7 on 2025-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0224_remove_historicalpallet_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="warehouse_unpacked_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="仓库确认拆柜完成时间"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="warehouse_unpacking_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="首次下载拆柜单变拆柜中时间"
            ),
        ),
        migrations.AddField(
            model_name="historicalretrieval",
            name="arrival_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="到仓位置"
            ),
        ),
        migrations.AddField(
            model_name="historicalretrieval",
            name="unpacking_status",
            field=models.CharField(
                choices=[("0", "未拆柜"), ("1", "已拆柜"), ("2", "拆柜中")],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="warehouse_unpacked_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="仓库确认拆柜完成时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="warehouse_unpacking_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="首次下载拆柜单变拆柜中时间"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="arrival_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="到仓位置"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="unpacking_status",
            field=models.CharField(
                choices=[("0", "未拆柜"), ("1", "已拆柜"), ("2", "拆柜中")],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
        migrations.AlterField(
            model_name="feedetail",
            name="niche_warehouse",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
