# Generated by Django 4.2.7 on 2025-09-12 07:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0224_historicalpackinglist_express_number_and_more"),
    ]

    operations = [

        migrations.AlterField(
            model_name="historicalretrieval",
            name="arrival_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="到仓位置"
            ),
        ),
        migrations.AlterField(
            model_name="historicalretrieval",
            name="unpacking_status",
            field=models.CharField(
                choices=[("0", "未拆柜"), ("1", "已拆柜")],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
        migrations.AlterField(
            model_name="retrieval",
            name="arrival_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="到仓位置"
            ),
        ),
        migrations.AlterField(
            model_name="retrieval",
            name="unpacking_status",
            field=models.CharField(
                choices=[("0", "未拆柜"), ("1", "已拆柜")],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
    ]
