# Generated by Django 4.2.7 on 2025-09-15 02:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0224_historicaloffload_warehouse_unpacked_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretrieval',
            name='arrival_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='到仓位置'),
        ),
        migrations.AddField(
            model_name='retrieval',
            name='arrival_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='到仓位置'),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='niche_warehouse',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
