# Generated by Django 4.2.7 on 2025-09-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0225_historicaloffload_warehouse_unpacked_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportUnpackingCabinets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_unpacking_id", models.CharField(max_length=255, null=True)),
                (
                    "download_num",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="导出拆柜单次数"
                    ),
                ),
                (
                    "download_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="导出拆柜单时间"
                    ),
                ),
                (
                    "container_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_unpacking_cabinets",
                        to="warehouse.container",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="export_unpacking_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="warehouse.exportunpackingcabinets",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="export_unpacking_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.exportunpackingcabinets",
            ),
        ),
    ]
