# Generated by Django 4.2.7 on 2025-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0225_fleetshipmentpallet_transfer_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransferlocation",
            name="note",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transferlocation",
            name="note",
            field=models.CharField(blank=True, null=True),
        ),
    ]
