# Generated by Django 4.2.7 on 2025-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0225_historicaloffload_warehouse_unpacked_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='drive_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='drive_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='warehouse_process_status',
            field=models.CharField(choices=[('check_in', 'Check In'), ('loading', '正在装柜'), ('shipped', '已出库')], default='check_in', max_length=20, verbose_name='仓库处理状态'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='drive_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='drive_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='warehouse_process_status',
            field=models.CharField(choices=[('check_in', 'Check In'), ('loading', '正在装柜'), ('shipped', '已出库')], default='check_in', max_length=20, verbose_name='仓库处理状态'),
        ),
    ]
