# Generated by Django 4.2.7 on 2025-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0226_fleet_drive_name_fleet_drive_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='shipped_cert_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='shipped_cert_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='warehouse_process_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('check_in', 'Check In'), ('loading', '正在装柜'), ('shipped', '已出库')], default='waiting', max_length=20, verbose_name='仓库处理状态'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='warehouse_process_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('check_in', 'Check In'), ('loading', '正在装柜'), ('shipped', '已出库')], default='waiting', max_length=20, verbose_name='仓库处理状态'),
        ),
    ]
