# Generated by Django 4.2.7 on 2025-08-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0226_historicaltransferlocation_note_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpallet",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="pallet",
            name="direction",
        ),
    ]
