# Generated by Django 4.2.7 on 2025-09-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0227_fleet_shipped_cert_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='drive_name',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='drive_phone',
            new_name='driver_phone',
        ),
        migrations.RenameField(
            model_name='historicalfleet',
            old_name='drive_name',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='historicalfleet',
            old_name='drive_phone',
            new_name='driver_phone',
        ),
    ]
