# Generated by Django 4.2.7 on 2025-09-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0228_rename_drive_name_fleet_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
