# Generated by Django 4.2.7 on 2025-09-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0229_fleet_trailer_number_historicalfleet_trailer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='abnormal_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='is_abnormal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='abnormal_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='is_abnormal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
