# Generated by Django 4.2.7 on 2025-09-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0226_exportunpackingcabinets_and_more"),
        ("warehouse", "0230_fleet_abnormal_reason_fleet_is_abnormal_and_more"),
    ]

    operations = []
