# Generated by Django 4.2.7 on 2025-09-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0231_merge_20250917_0240"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="is_abnormal",
        ),
        migrations.RemoveField(
            model_name="historicalfleet",
            name="is_abnormal",
        ),
        migrations.RemoveField(
            model_name="historicalretrieval",
            name="arrival_location",
        ),
        migrations.RemoveField(
            model_name="historicalretrieval",
            name="unpacking_status",
        ),
        migrations.RemoveField(
            model_name="retrieval",
            name="arrival_location",
        ),
        migrations.RemoveField(
            model_name="retrieval",
            name="unpacking_status",
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="arrival_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="到仓位置"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="unpacking_status",
            field=models.CharField(
                choices=[("0", "未拆柜"), ("1", "已拆柜"), ("2", "拆柜中")],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="arrival_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="到仓位置"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="unpacking_status",
            field=models.CharField(
                choices=[("0", "未拆柜"), ("1", "已拆柜"), ("2", "拆柜中")],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="warehouse_process_status",
            field=models.CharField(
                choices=[
                    ("waiting", "waiting"),
                    ("check_in", "Check In"),
                    ("loading", "正在装柜"),
                    ("shipped", "已出库"),
                    ("abnormal", "已异常"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="仓库处理状态",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfleet",
            name="warehouse_process_status",
            field=models.CharField(
                choices=[
                    ("waiting", "waiting"),
                    ("check_in", "Check In"),
                    ("loading", "正在装柜"),
                    ("shipped", "已出库"),
                    ("abnormal", "已异常"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="仓库处理状态",
            ),
        ),
    ]
