# Generated by Django 4.2.7 on 2025-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0232_remove_fleet_is_abnormal_and_more.'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='is_abnormal',
        ),
        migrations.RemoveField(
            model_name='historicalfleet',
            name='is_abnormal',
        ),
        migrations.AlterField(
            model_name='fleet',
            name='warehouse_process_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('check_in', 'Check In'), ('loading', '正在装柜'), ('shipped', '已出库'), ('abnormal', '已异常')], default='waiting', max_length=20, verbose_name='仓库处理状态'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='warehouse_process_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('check_in', 'Check In'), ('loading', '正在装柜'), ('shipped', '已出库'), ('abnormal', '已异常')], default='waiting', max_length=20, verbose_name='仓库处理状态'),
        ),
    ]
