# Generated by Django 4.2.7 on 2025-09-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0232_remove_fleet_is_abnormal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="image_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="offload",
            name="image_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="offload_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="warehouse.offload",
            ),
        ),
    ]
