# Generated by Django 4.2.7 on 2025-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0233_historicaloffload_image_link_offload_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='pre_load',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='pre_load',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
