# Generated by Django 4.2.7 on 2025-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0234_fleet_pre_load_historicalfleet_pre_load"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="historicaloffload",
            name="uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="回传拆柜数据上传时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="回传拆柜数据上传时间"
            ),
        ),
    ]
