# Generated by Django 4.2.7 on 2025-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0235_remove_fleet_pre_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetshipmentpallet',
            name='is_recorded',
            field=models.BooleanField(default=False, verbose_name='是否已记录'),
        ),
        migrations.AddField(
            model_name='historicalfleetshipmentpallet',
            name='is_recorded',
            field=models.BooleanField(default=False, verbose_name='是否已记录'),
        ),
    ]
