# Generated by Django 4.2.7 on 2025-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0236_fleetshipmentpallet_is_recorded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicestatus",
            name="payable_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="应付待审核通过时间"
            ),
        ),
        migrations.AddField(
            model_name="invoicestatus",
            name="payable_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="应付待审核通过时间"
            ),
        ),
    ]
