# Generated by Django 4.2.7 on 2025-10-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0237_historicalinvoicestatus_payable_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="offload_note",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="回传拆柜数据备注"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="offload_note",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="回传拆柜数据备注"
            ),
        ),
    ]
