# Generated by Django 4.2.7 on 2025-10-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0238_historicaloffload_offload_note_offload_offload_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="note_preport_dispatch",
            field=models.TextField(
                blank=True, null=True, verbose_name="货柜进度汇总备注"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="note_preport_dispatch",
            field=models.TextField(
                blank=True, null=True, verbose_name="货柜进度汇总备注"
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="warehouse_process_status",
            field=models.CharField(
                choices=[
                    ("waiting", "waiting"),
                    ("check_in", "Check In"),
                    ("loading", "正在装柜"),
                    ("shipped", "已出库"),
                    ("proof_uploaded", "已上传凭证"),
                    ("abnormal", "已异常"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="仓库处理状态",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfleet",
            name="warehouse_process_status",
            field=models.CharField(
                choices=[
                    ("waiting", "waiting"),
                    ("check_in", "Check In"),
                    ("loading", "正在装柜"),
                    ("shipped", "已出库"),
                    ("proof_uploaded", "已上传凭证"),
                    ("abnormal", "已异常"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="仓库处理状态",
            ),
        ),
    ]
