# Generated by Django 4.2.7 on 2025-10-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0239_historicalretrieval_note_preport_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='shipment_cargo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_cargo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
