# Generated by Django 4.2.7 on 2025-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0240_historicalshipment_shipment_cargo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpallet',
            name='fba_id',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpallet',
            name='ref_id',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpallet',
            name='shipping_mark',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fba_id',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='ref_id',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='shipping_mark',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
