# Generated by Django 4.2.7 on 2025-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0241_alter_historicalpallet_fba_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='is_print_label',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_print_label',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
