# Generated by Django 4.2.7 on 2025-10-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0242_historicalshipment_is_print_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpallet',
            name='is_dropped_pallet',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='is_dropped_pallet',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
