# Generated by Django 4.2.7 on 2025-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0243_historicalpallet_is_dropped_pallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("unfinished", "未完成"),
                    ("completed", "已完成"),
                    ("checked", "已检查"),
                ],
                default="unfinished",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unfinished", "未完成"),
                    ("completed", "已完成"),
                    ("checked", "已检查"),
                ],
                default="unfinished",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
