# Generated by Django 4.2.7 on 2025-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0244_historicalorder_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpallet',
            name='note_sp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='note_sp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
