# Generated by Django 4.2.7 on 2025-10-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0245_historicalpallet_note_sp_pallet_note_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='note_sp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='note_sp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
