# Generated by Django 4.2.7 on 2025-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0246_historicalpackinglist_note_sp_packinglist_note_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='is_virtual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='is_virtual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
