# Generated by Django 4.2.7 on 2025-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0247_fleet_is_virtual_historicalfleet_is_virtual"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="retrieval_carrier_planned",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="计划提柜供应商"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="retrieval_carrier_planned",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="计划提柜供应商"
            ),
        ),
    ]
