# Generated by Django 4.2.7 on 2025-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0248_historicalretrieval_retrieval_carrier_planned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="retrieval_delegation_status",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="调度委托状态"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="retrieval_delegation_status",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="调度委托状态"
            ),
        ),
    ]
