# Generated by Django 4.2.7 on 2025-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0249_historicalretrieval_retrieval_delegation_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalretrieval",
            name="retrieval_delegation_status",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="调度委托状态"
            ),
        ),
        migrations.AlterField(
            model_name="retrieval",
            name="retrieval_delegation_status",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="调度委托状态"
            ),
        ),
    ]
