# Generated by Django 4.2.7 on 2025-11-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0250_alter_historicalretrieval_retrieval_delegation_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="retrieval_cabinet_arrangement_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="货柜汇总页面提柜安排时间"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="retrieval_cabinet_arrangement_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="货柜汇总页面提柜安排时间"
            ),
        ),
    ]
