# Generated by Django 4.2.7 on 2025-11-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0252_historicalretrieval_planned_release_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="actual_release_status",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="oct页面实际放行状态"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="actual_release_status",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="oct页面实际放行状态"
            ),
        ),
    ]
