# Generated by Django 4.2.7 on 2025-11-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0253_historicalretrieval_actual_release_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
