# Generated by Django 4.2.7 on 2025-11-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0254_historicalshipment_pickup_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="is_abnormal_state",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="是否为异常状态"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontainer",
            name="is_abnormal_state",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="是否为异常状态"
            ),
        ),
    ]
