# Generated by Django 4.2.7 on 2025-11-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0255_container_is_abnormal_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="t49_empty_returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalretrieval",
            name="t49_pod_full_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalvessel",
            name="vessel_imo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="t49_empty_returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="t49_pod_full_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="vessel_imo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
