# Generated by Django 4.2.7 on 2025-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0256_historicalretrieval_t49_empty_returned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalretrieval",
            name="planned_release_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实际放行时间"
            ),
        ),
        migrations.AlterField(
            model_name="retrieval",
            name="planned_release_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实际放行时间"
            ),
        ),
    ]
