# Generated by Django 4.2.7 on 2025-11-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0257_alter_historicalretrieval_planned_release_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalretrieval",
            name="generous_and_wide_target_retrieval_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="大方广预计提柜时间"
            ),
        ),
        migrations.AddField(
            model_name="retrieval",
            name="generous_and_wide_target_retrieval_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="大方广预计提柜时间"
            ),
        ),
    ]
