# Generated by Django 4.2.7 on 2025-11-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0258_historicalretrieval_generous_and_wide_target_retrieval_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerAutomateWebhookRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=100, null=True)),
                ("header", models.JSONField(blank=True, null=True)),
                ("body", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Power Automate Webhook Raw",
                "verbose_name_plural": "Power Automate Webhook Raw",
            },
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="ltl_bol_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="ltl_label_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="ltl_bol_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="ltl_label_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
