# Generated by Django 4.2.7 on 2025-11-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0259_powerautomatewebhookraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicestatus',
            name='delivery_other_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoicestatus',
            name='delivery_public_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoicestatus',
            name='finance_status',
            field=models.CharField(choices=[('unstarted', '未开始'), ('tobeconfirmed', '待确认'), ('confirmed', '已完成')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoicestatus',
            name='preport_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('pending_review', '待组长审核'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoicestatus',
            name='warehouse_other_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinvoicestatus',
            name='warehouse_public_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='delivery_other_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='delivery_public_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='finance_status',
            field=models.CharField(choices=[('unstarted', '未开始'), ('tobeconfirmed', '待确认'), ('confirmed', '已完成')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='preport_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('pending_review', '待组长审核'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='warehouse_other_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='warehouse_public_status',
            field=models.CharField(choices=[('unstarted', '未录入'), ('in_progress', '录入中'), ('completed', '已完成'), ('rejected', '已驳回')], default='unstarted', max_length=20),
        ),
    ]
