# Generated by Django 4.2.7 on 2025-11-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0260_historicalinvoicestatus_delivery_other_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerautomatewebhookraw",
            name="response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
