# Generated by Django 4.2.7 on 2025-11-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0261_powerautomatewebhookraw_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="offload_at_container",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="货柜汇总页面拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="offload_at_container",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="货柜汇总页面拆柜时间"
            ),
        ),
    ]
