# Generated by Django 4.2.7 on 2025-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0262_historicaloffload_offload_at_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvessel',
            name='destination_port_t49',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='origin_port_t49',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='vessel_eta_t49',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='vessel_etd_t49',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='vessel_t49',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='destination_port_t49',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='origin_port_t49',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_eta_t49',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_etd_t49',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_t49',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoicestatus',
            name='finance_status',
            field=models.CharField(choices=[('unstarted', '未开始'), ('tobeconfirmed', '待确认'), ('completed', '已完成')], default='unstarted', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='finance_status',
            field=models.CharField(choices=[('unstarted', '未开始'), ('tobeconfirmed', '待确认'), ('completed', '已完成')], default='unstarted', max_length=20),
        ),
    ]
