# Generated by Django 4.2.7 on 2025-11-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0263_historicalvessel_destination_port_t49_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='is_notified_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_notified_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
