# Generated by Django 4.2.7 on 2025-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0264_historicalshipment_is_notified_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="do_sent_new",
            field=models.CharField(
                blank=True,
                choices=[
                    ("未提供", "未提供"),
                    ("已催促", "已催促"),
                    ("已提供", "已提供"),
                ],
                default="未提供",
                max_length=10,
                verbose_name="是否提供DO",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="do_sent_new",
            field=models.CharField(
                blank=True,
                choices=[
                    ("未提供", "未提供"),
                    ("已催促", "已催促"),
                    ("已提供", "已提供"),
                ],
                default="未提供",
                max_length=10,
                verbose_name="是否提供DO",
            ),
        ),
    ]
