# Generated by Django 4.2.7 on 2025-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0265_historicalorder_do_sent_new_order_do_sent_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvessel',
            name='vessel_mmsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_mmsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
