# Generated by Django 4.2.7 on 2025-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0266_historicalvessel_vessel_mmsi_vessel_vessel_mmsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvessel',
            name='add_to_shipxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vessel',
            name='add_to_shipxy',
            field=models.BooleanField(default=False),
        ),
    ]
