# Generated by Django 4.2.7 on 2025-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0268_invoicev2_invoicestatusv2_invoiceitemv2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
