# Generated by Django 4.2.7 on 2025-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0269_historicalinvoicev2_created_at_invoicev2_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='manually_order_type',
            field=models.CharField(choices=[('undefined', '未定义'), ('转运', '转运'), ('转运组合', '转运组合')], default='undefined', max_length=20, verbose_name='人为调整订单类型'),
        ),
        migrations.AddField(
            model_name='historicalcontainer',
            name='manually_order_type',
            field=models.CharField(choices=[('undefined', '未定义'), ('转运', '转运'), ('转运组合', '转运组合')], default='undefined', max_length=20, verbose_name='人为调整订单类型'),
        ),
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='surcharges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='surcharges',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
