# Generated by Django 4.2.7 on 2025-12-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0270_container_manually_order_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="zipcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="zipcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
