# Generated by Django 4.2.7 on 2025-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0271_alter_historicalpackinglist_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
