# Generated by Django 4.2.7 on 2025-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0270_container_manually_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoicev2',
            name='receivable_delivery_amount',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicev2',
            name='receivable_warehouse_amount',
        ),
        migrations.RemoveField(
            model_name='invoicev2',
            name='receivable_delivery_amount',
        ),
        migrations.RemoveField(
            model_name='invoicev2',
            name='receivable_warehouse_amount',
        ),
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='receivable_delivery_other_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='receivable_delivery_public_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='receivable_wh_other_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='receivable_wh_public_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='receivable_delivery_other_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='receivable_delivery_public_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='receivable_wh_other_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='receivable_wh_public_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
