# Generated by Django 4.2.7 on 2025-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0273_remove_historicalinvoicev2_receivable_delivery_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="destination",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="destination",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
