# Generated by Django 4.2.7 on 2025-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0274_alter_historicalpackinglist_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
