# Generated by Django 4.2.7 on 2025-12-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0275_alter_historicalpackinglist_po_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='registered_user',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='statement_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.invoicestatement'),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='registered_user',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='statement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.invoicestatement'),
        ),
    ]
