# Generated by Django 4.2.7 on 2025-12-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0276_historicalinvoiceitemv2_registered_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='regionPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='regionPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
