# Generated by Django 4.2.7 on 2025-12-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0277_historicalinvoiceitemv2_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='cbm_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='cbm_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
