# Generated by Django 4.2.7 on 2025-12-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0278_historicalinvoiceitemv2_cbm_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='carrier_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl承运公司'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_verify',
            field=models.BooleanField(default=True, verbose_name='ltl组是否核实'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='pl_ltl_bol_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-bol'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='pl_ltl_pro_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-pro'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='carrier_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl承运公司'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_verify',
            field=models.BooleanField(default=True, verbose_name='ltl组是否核实'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='pl_ltl_bol_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-bol'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='pl_ltl_pro_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-pro'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitemv2',
            name='item_category',
            field=models.CharField(choices=[('preport', '港前'), ('warehouse_public', '公仓库内'), ('warehouse_other', '私仓库内'), ('delivery_public', '公仓派送'), ('delivery_other', '私仓派送'), ('activation_fee', '激活费')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalinvoicev2',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='账单创建时间'),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='item_category',
            field=models.CharField(choices=[('preport', '港前'), ('warehouse_public', '公仓库内'), ('warehouse_other', '私仓库内'), ('delivery_public', '公仓派送'), ('delivery_other', '私仓派送'), ('activation_fee', '激活费')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='账单创建时间'),
        ),
    ]
