# Generated by Django 4.2.7 on 2025-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0279_historicalpackinglist_carrier_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackinglist',
            name='ltl_verify',
            field=models.BooleanField(default=False, verbose_name='ltl组是否核实'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='ltl_verify',
            field=models.BooleanField(default=False, verbose_name='ltl组是否核实'),
        ),
    ]
