# Generated by Django 4.2.7 on 2025-12-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0280_alter_historicalpackinglist_ltl_verify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='PickupAddr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客提详细地址'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='PickupAddr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客提详细地址'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='carrier_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl承运公司'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='plt_ltl_bol_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-bol'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='plt_ltl_pro_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-pro'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='PickupAddr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客提详细地址'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='PickupAddr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客提详细地址'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='carrier_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl承运公司'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='plt_ltl_bol_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-bol'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='plt_ltl_pro_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl-pro'),
        ),
    ]
