# Generated by Django 4.2.7 on 2025-12-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0281_historicalpackinglist_pickupaddr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='est_pickup_time',
            field=models.DateField(blank=True, null=True, verbose_name='自提预计提货时间'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='est_pickup_time',
            field=models.DateField(blank=True, null=True, verbose_name='自提预计提货时间'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='est_pickup_time',
            field=models.DateField(blank=True, null=True, verbose_name='自提预计提货时间'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='est_pickup_time',
            field=models.DateField(blank=True, null=True, verbose_name='自提预计提货时间'),
        ),
    ]
