# Generated by Django 4.2.7 on 2025-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0282_historicalpackinglist_est_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的成本'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_quote',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的报价'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的成本'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_quote',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的报价'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的成本'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_quote',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的报价'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的成本'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_quote',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的报价'),
        ),
    ]
