# Generated by Django 4.2.7 on 2025-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0283_historicalpackinglist_ltl_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='ltl_shipping_tracking',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='LTL物流跟踪进度'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='ltl_shipping_tracking',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='LTL物流跟踪进度'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_follow_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl跟进状态'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_follow_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl跟进状态'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_follow_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl跟进状态'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_follow_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ltl跟进状态'),
        ),
    ]
