# Generated by Django 4.2.7 on 2025-12-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0285_fleet_pod_to_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='pod_to_customer',
        ),
        migrations.RemoveField(
            model_name='historicalfleet',
            name='pod_to_customer',
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='pod_to_customer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='LTL是否将POD传给客户'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_to_customer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='LTL是否将POD传给客户'),
        ),
    ]
