# Generated by Django 4.2.7 on 2025-12-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0286_remove_fleet_pod_to_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="container_number",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="warehouse.container",
            ),
        ),
    ]
