# Generated by Django 4.2.7 on 2026-01-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0287_alter_order_container_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoiceitemv2',
            name='shipping_marks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='shipping_marks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
