# Generated by Django 4.2.7 on 2026-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0288_historicalinvoiceitemv2_shipping_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoiceitemv2',
            name='shipping_marks',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='shipping_marks',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
