# Generated by Django 4.2.7 on 2026-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0289_alter_historicalinvoiceitemv2_shipping_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_contact_method',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl预约送货联系方式'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_cost_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl成本备注'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_quote_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl报价备注'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_release_command',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl未放行时客户指令'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_contact_method',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl预约送货联系方式'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_cost_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl成本备注'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_quote_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl报价备注'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_release_command',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl未放行时客户指令'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_contact_method',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl预约送货联系方式'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_cost_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl成本备注'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_quote_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl报价备注'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_release_command',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl未放行时客户指令'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_contact_method',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl预约送货联系方式'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_cost_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl成本备注'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_quote_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl报价备注'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_release_command',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl未放行时客户指令'),
        ),
        migrations.AlterField(
            model_name='historicalpackinglist',
            name='ltl_follow_status',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl跟进状态'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='ltl_follow_status',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl跟进状态'),
        ),
    ]
