# Generated by Django 4.2.7 on 2026-01-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0290_historicalpackinglist_ltl_contact_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackinglist',
            name='ltl_cost',
        ),
        migrations.RemoveField(
            model_name='historicalpackinglist',
            name='ltl_cost_note',
        ),
        migrations.RemoveField(
            model_name='historicalpackinglist',
            name='ltl_quote',
        ),
        migrations.RemoveField(
            model_name='historicalpackinglist',
            name='ltl_quote_note',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='ltl_cost',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='ltl_cost_note',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='ltl_quote',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='ltl_quote_note',
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='del_qty',
            field=models.FloatField(blank=True, null=True, verbose_name='私仓派送费的数量'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='del_qty',
            field=models.FloatField(blank=True, null=True, verbose_name='私仓派送费的数量'),
        ),
    ]
