# Generated by Django 4.2.7 on 2026-01-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0291_remove_historicalpackinglist_ltl_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoiceitemv2",
            name="carrier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="供应商"
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoiceitemv2",
            name="write_off_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=12,
                null=True,
                verbose_name="核销金额",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoiceitemv2",
            name="write_off_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="核销时间"
            ),
        ),
        migrations.AddField(
            model_name="invoiceitemv2",
            name="carrier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="供应商"
            ),
        ),
        migrations.AddField(
            model_name="invoiceitemv2",
            name="write_off_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=12,
                null=True,
                verbose_name="核销金额",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitemv2",
            name="write_off_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="核销时间"
            ),
        ),
    ]
