# Generated by Django 4.2.7 on 2026-01-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0292_historicalinvoiceitemv2_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpallet',
            name='unit_quote',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的单板报价'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='unit_quote',
            field=models.FloatField(blank=True, null=True, verbose_name='ltl的单板报价'),
        ),
    ]
