# Generated by Django 4.2.7 on 2026-01-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0293_historicalpallet_unit_quote_pallet_unit_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpallet',
            old_name='unit_quote',
            new_name='ltl_unit_quote',
        ),
        migrations.RenameField(
            model_name='pallet',
            old_name='unit_quote',
            new_name='ltl_unit_quote',
        ),
    ]
