# Generated by Django 4.2.7 on 2026-01-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0294_rename_unit_quote_historicalpallet_ltl_unit_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_plt_size_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ltl-板子尺寸备注'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_plt_size_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ltl-板子尺寸备注'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitemv2',
            name='item_category',
            field=models.CharField(choices=[('preport', '港前'), ('warehouse_public', '公仓库内'), ('warehouse_other', '私仓库内'), ('delivery_public', '公仓派送'), ('delivery_other', '私仓派送'), ('activation_fee', '激活费'), ('combina_extra_fee', '组合费额外费用')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='item_category',
            field=models.CharField(choices=[('preport', '港前'), ('warehouse_public', '公仓库内'), ('warehouse_other', '私仓库内'), ('delivery_public', '公仓派送'), ('delivery_other', '私仓派送'), ('activation_fee', '激活费'), ('combina_extra_fee', '组合费额外费用')], max_length=30),
        ),
    ]
