# Generated by Django 4.2.7 on 2026-01-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0295_historicalpallet_ltl_plt_size_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpackinglist',
            old_name='pl_ltl_bol_num',
            new_name='ltl_bol_num',
        ),
        migrations.RenameField(
            model_name='historicalpackinglist',
            old_name='pl_ltl_pro_num',
            new_name='ltl_pro_num',
        ),
        migrations.RenameField(
            model_name='historicalpallet',
            old_name='plt_ltl_bol_num',
            new_name='ltl_bol_num',
        ),
        migrations.RenameField(
            model_name='historicalpallet',
            old_name='plt_ltl_pro_num',
            new_name='ltl_pro_num',
        ),
        migrations.RenameField(
            model_name='packinglist',
            old_name='pl_ltl_bol_num',
            new_name='ltl_bol_num',
        ),
        migrations.RenameField(
            model_name='packinglist',
            old_name='pl_ltl_pro_num',
            new_name='ltl_pro_num',
        ),
        migrations.RenameField(
            model_name='pallet',
            old_name='plt_ltl_bol_num',
            new_name='ltl_bol_num',
        ),
        migrations.RenameField(
            model_name='pallet',
            old_name='plt_ltl_pro_num',
            new_name='ltl_pro_num',
        ),
    ]
