# Generated by Django 4.2.7 on 2026-01-20 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "warehouse",
            "0296_rename_pl_ltl_bol_num_historicalpackinglist_ltl_bol_num_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="cost_input_time",
            field=models.DateTimeField(
                blank=True,
                help_text="录入/更新该批次成本的时间",
                null=True,
                verbose_name="成本录入时间",
            ),
        ),
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                help_text="录入/更新成本的操作人员",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人员",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="cost_input_time",
            field=models.DateTimeField(
                blank=True,
                help_text="录入/更新该批次成本的时间",
                null=True,
                verbose_name="成本录入时间",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="录入/更新成本的操作人员",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人员",
            ),
        ),
    ]
