# Generated by Django 4.2.7 on 2026-01-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0297_fleetshipmentpallet_cost_input_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleetshipmentpallet",
            name="shipment_batch_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleetshipmentpallets",
                to="warehouse.shipment",
            ),
        ),
    ]
