# Generated by Django 4.2.7 on 2026-01-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0298_alter_fleetshipmentpallet_shipment_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='fleet_cost_back',
            field=models.FloatField(blank=True, null=True, verbose_name='退回费用'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='fleet_cost_back',
            field=models.FloatField(blank=True, null=True, verbose_name='退回费用'),
        ),
    ]
