# Generated by Django 4.2.7 on 2026-01-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0299_fleet_fleet_cost_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="费用名称"
            ),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="费用名称"
            ),
        ),
    ]
