# Generated by Django 4.2.7 on 2026-02-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0300_fleetshipmentpallet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_correlation_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl一提多卸关联关系'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_correlation_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl一提多卸关联关系'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_correlation_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl一提多卸关联关系'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_correlation_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ltl一提多卸关联关系'),
        ),
    ]
