# Generated by Django 4.2.7 on 2026-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0301_historicalpackinglist_ltl_correlation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="note",
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="note",
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
