# Generated by Django 4.2.7 on 2026-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0302_alter_historicalpackinglist_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="fleet_verify_status",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="ltl录入成本页面核实状态",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleet",
            name="fleet_verify_status",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="ltl录入成本页面核实状态",
            ),
        ),
    ]
