# Generated by Django 4.2.7 on 2026-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0303_fleet_fleet_verify_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='shipment_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='公仓排约备注'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='shipment_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='公仓排约备注'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='shipment_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='公仓排约备注'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='shipment_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='公仓排约备注'),
        ),
    ]
