# Generated by Django 4.2.7 on 2026-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0304_historicalpackinglist_shipment_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="train_related",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ltl关联车次为一提多卸",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleet",
            name="train_related",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ltl关联车次为一提多卸",
            ),
        ),
    ]
