# Generated by Django 4.2.7 on 2026-03-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0305_fleet_train_related_historicalfleet_train_related"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpallet",
            name="note",
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="note",
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
