# Generated by Django 4.2.7 on 2026-03-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0306_alter_historicalpallet_note_alter_pallet_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='Supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='Supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
