# Generated by Django 4.2.7 on 2026-03-24 03:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0306_alter_historicalpallet_note_alter_pallet_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_delivery_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                null=True,
                verbose_name="派送成本费用",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_delivery_refund",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                null=True,
                verbose_name="派送退回费用",
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_delivery_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                null=True,
                verbose_name="派送成本费用",
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_delivery_refund",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                null=True,
                verbose_name="派送退回费用",
            ),
        ),
    ]
