# Generated by Django 4.2.7 on 2026-03-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0307_fleet_supplier_historicalfleet_supplier"),
        ("warehouse", "0307_historicalinvoicev2_payable_delivery_cost_and_more"),
    ]

    operations = []
