# Generated by Django 4.2.7 on 2026-03-26 07:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0308_merge_20260324_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_delivery_transfer",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                null=True,
                verbose_name="派送转仓费用",
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_delivery_transfer",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                null=True,
                verbose_name="派送转仓费用",
            ),
        ),
    ]
