# Generated by Django 4.2.7 on 2026-03-30 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0309_historicalinvoicev2_payable_delivery_transfer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetDoseNot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_number",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="提货号"
                    ),
                ),
                (
                    "shipment_batch_number",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="出库批次号"
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="预约ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_dose_not",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "ftl上传车次不在的表",
                "verbose_name_plural": "ftl上传车次不在的表",
                "ordering": ["-created_at"],
            },
        ),
    ]
