# Generated by Django 4.2.7 on 2026-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0310_fleetdosenot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="fba_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="ref_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="shipping_mark",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="fba_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="ref_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="shipping_mark",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
