# Generated by Django 4.2.7 on 2026-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0311_alter_historicalpackinglist_fba_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="destination",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpackinglist",
            name="fba_id",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="destination",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="fba_id",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
