# Generated by Django 4.2.7 on 2026-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0312_alter_historicalpackinglist_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpochecketaseven",
            name="fba_id",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpochecketaseven",
            name="ref_id",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpochecketaseven",
            name="shipping_mark",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="pochecketaseven",
            name="fba_id",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="pochecketaseven",
            name="ref_id",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="pochecketaseven",
            name="shipping_mark",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
