# Generated by Django 4.2.7 on 2026-03-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0313_alter_historicalpochecketaseven_fba_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="fleet_transfer_cost",
            field=models.FloatField(blank=True, null=True, verbose_name="转仓费用"),
        ),
        migrations.AddField(
            model_name="historicalfleet",
            name="fleet_transfer_cost",
            field=models.FloatField(blank=True, null=True, verbose_name="转仓费用"),
        ),
    ]
