# Generated by Django 5.1.1 on 2026-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0314_fleet_fleet_transfer_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaerskPriceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_id', models.CharField(max_length=200, null=True)),
                ('is_user_exclusive', models.BooleanField(default=False, verbose_name='用户专属')),
                ('exclusive_user', models.CharField(blank=True, max_length=2000, null=True, verbose_name='专属用户')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('increase_percentage', models.FloatField(verbose_name='涨幅百分比')),
            ],
        ),
    ]
