# Generated by Django 4.2.7 on 2026-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0315_maerskpricerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpackinglist",
            name="office_note",
            field=models.CharField(
                blank=True, max_length=6000, null=True, verbose_name="客服备注"
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="office_note",
            field=models.CharField(
                blank=True, max_length=6000, null=True, verbose_name="客服备注"
            ),
        ),
    ]
