# Generated by Django 4.2.7 on 2026-04-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0316_historicalpackinglist_office_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='check_by_leader',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='组长是否核对了出库的货物'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='check_by_leader',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='组长是否核对了出库的货物'),
        ),
    ]
