# Generated by Django 4.2.7 on 2026-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0317_fleet_check_by_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='is_master_bill',
            field=models.BooleanField(default=False, verbose_name='是否是主账单'),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='is_master_bill',
            field=models.BooleanField(default=False, verbose_name='是否是主账单'),
        ),
    ]
