# Generated by Django 4.2.7 on 2026-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0318_historicalinvoicev2_is_master_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='is_virtual_sp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='虚构的约'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_virtual_sp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='虚构的约'),
        ),
    ]
