# Generated by Django 4.2.7 on 2026-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0319_historicalshipment_is_virtual_sp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicev2',
            name='payout_total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='赔付的费用'),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='payout_total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='赔付的费用'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitemv2',
            name='item_category',
            field=models.CharField(choices=[('preport', '港前'), ('warehouse_public', '公仓库内'), ('warehouse_other', '私仓库内'), ('delivery_public', '公仓派送'), ('delivery_other', '私仓派送'), ('activation_fee', '激活费'), ('combina_extra_fee', '组合费额外费用'), ('payout_fee', '赔付费用')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='item_category',
            field=models.CharField(choices=[('preport', '港前'), ('warehouse_public', '公仓库内'), ('warehouse_other', '私仓库内'), ('delivery_public', '公仓派送'), ('delivery_other', '私仓派送'), ('activation_fee', '激活费'), ('combina_extra_fee', '组合费额外费用'), ('payout_fee', '赔付费用')], max_length=30),
        ),
    ]
