# Generated by Django 4.2.7 on 2026-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0320_historicalinvoicev2_payout_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='shipping_order_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_order_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
