# Generated by Django 4.2.7 on 2026-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0321_historicalshipment_shipping_order_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ltl询价的地址'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的城市'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的州'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_zipcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的邮编'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ltl询价的地址'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的城市'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的州'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_zipcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的邮编'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ltl询价的地址'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的城市'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的州'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_zipcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的邮编'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ltl询价的地址'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的城市'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的州'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_zipcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价的邮编'),
        ),
    ]
