# Generated by Django 4.2.7 on 2026-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0322_historicalpackinglist_ltl_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_address_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价地址类型'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_address_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价地址类型'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_address_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价地址类型'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_address_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl询价地址类型'),
        ),
    ]
