# Generated by Django 4.2.7 on 2026-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0323_historicalpackinglist_ltl_address_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="offload_other_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="offload_other_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓拆柜时间"
            ),
        ),
    ]
