# Generated by Django 4.2.7 on 2026-04-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0323_historicalpackinglist_ltl_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='ltl_supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl供应商'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='ltl_supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl供应商'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='ltl_supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl供应商'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ltl_supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ltl供应商'),
        ),
    ]
