# Generated by Django 5.1.1 on 2026-04-27 06:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0324_historicalpackinglist_ltl_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPalletException',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('unpack', '拆柜异常'), ('appointment', '拿约异常')], max_length=50, verbose_name='异常类型')),
                ('exception_reason', models.CharField(max_length=500, verbose_name='异常原因')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.pallet', verbose_name='关联Pallet')),
            ],
            options={
                'verbose_name': 'historical Pallet异常',
                'verbose_name_plural': 'historical Pallet异常',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PalletException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('unpack', '拆柜异常'), ('appointment', '拿约异常')], max_length=50, verbose_name='异常类型')),
                ('exception_reason', models.CharField(max_length=500, verbose_name='异常原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='warehouse.pallet', verbose_name='关联Pallet')),
            ],
            options={
                'verbose_name': 'Pallet异常',
                'verbose_name_plural': 'Pallet异常',
                'indexes': [models.Index(fields=['pallet'], name='warehouse_p_pallet__21b242_idx'), models.Index(fields=['exception_type'], name='warehouse_p_excepti_f5d9d9_idx')],
            },
        ),
    ]
