# Generated by Django 4.2.7 on 2026-04-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0324_historicaloffload_offload_other_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="other_selfdelivery_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la私仓卡车派送拆柜板子总数"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="other_selfpick_cargos_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la私仓客户自提拆柜板子总数"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="public_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la公仓拆柜板子总数"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="other_selfdelivery_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la私仓卡车派送拆柜板子总数"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="other_selfpick_cargos_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la私仓客户自提拆柜板子总数"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="public_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la公仓拆柜板子总数"
            ),
        ),
    ]
