# Generated by Django 4.2.7 on 2026-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0325_historicaloffload_other_selfdelivery_total_pallet_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaloffload",
            name="offload_other_at",
        ),
        migrations.RemoveField(
            model_name="offload",
            name="offload_other_at",
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="offload_other_selfdelivery_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓卡车派送拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="offload_other_selfpick_cargos_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓客户自提拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="offload_other_selfdelivery_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓卡车派送拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="offload_other_selfpick_cargos_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓客户自提拆柜时间"
            ),
        ),
    ]
