# Generated by Django 4.2.7 on 2026-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0325_remove_historicalinvoiceitemv2_write_off_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetshipmentpallet",
            name="finance_note",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="财务备注"
            ),
        ),
        migrations.AddField(
            model_name="historicalfleetshipmentpallet",
            name="finance_note",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="财务备注"
            ),
        ),
    ]
