# Generated by Django 4.2.7 on 2026-04-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0326_fleetshipmentpallet_finance_note_and_more"),
        ("warehouse", "0326_remove_historicaloffload_offload_other_at_and_more"),
    ]

    operations = []
