# Generated by Django 4.2.7 on 2026-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0327_merge_20260427_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="delivery_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalabnormaloffloadstatus",
            name="delivery_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
