# Generated by Django 4.2.7 on 2026-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0328_abnormaloffloadstatus_delivery_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="warehosue",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalabnormaloffloadstatus",
            name="warehosue",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
