# Generated by Django 4.2.7 on 2026-04-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0329_abnormaloffloadstatus_warehosue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abnormaloffloadstatus",
            name="warehosue",
        ),
        migrations.RemoveField(
            model_name="historicalabnormaloffloadstatus",
            name="warehosue",
        ),
    ]
