# Generated by Django 4.2.7 on 2026-04-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0327_historicalpalletexception_palletexception"),
        ("warehouse", "0330_remove_abnormaloffloadstatus_warehosue_and_more"),
    ]

    operations = []
