# Generated by Django 4.2.7 on 2026-04-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0331_merge_20260428_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloffload",
            name="offload_other_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="historicaloffload",
            name="other_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la私仓拆柜板子总数"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="offload_other_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="私仓拆柜时间"
            ),
        ),
        migrations.AddField(
            model_name="offload",
            name="other_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la私仓拆柜板子总数"
            ),
        ),
    ]
