# Generated by Django 4.2.7 on 2026-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0333_historicalinvoiceitemv2_write_off_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zem_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='zem_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
