# Generated by Django 4.2.7 on 2026-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0334_alter_customer_zem_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloffload",
            name="unpacking_status",
            field=models.CharField(
                choices=[
                    ("0", "未拆柜"),
                    ("1", "已拆柜"),
                    ("2", "拆柜中"),
                    ("3", "已到仓"),
                    ("4", "已报空"),
                ],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
        migrations.AlterField(
            model_name="offload",
            name="unpacking_status",
            field=models.CharField(
                choices=[
                    ("0", "未拆柜"),
                    ("1", "已拆柜"),
                    ("2", "拆柜中"),
                    ("3", "已到仓"),
                    ("4", "已报空"),
                ],
                default="0",
                max_length=10,
                verbose_name="拆柜状态",
            ),
        ),
    ]
