# Generated by Django 4.2.7 on 2026-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0335_alter_historicaloffload_unpacking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoicestatusv2',
            name='finance_status',
            field=models.CharField(choices=[('unstarted', '未开始'), ('tobeconfirmed', '回退'), ('completed', '已完成')], default='unstarted', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicestatusv2',
            name='finance_status',
            field=models.CharField(choices=[('unstarted', '未开始'), ('tobeconfirmed', '回退'), ('completed', '已完成')], default='unstarted', max_length=20),
        ),
    ]
