# Generated by Django 4.2.7 on 2026-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0336_alter_historicalinvoicestatusv2_finance_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloffload",
            name="other_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la,sav私仓拆柜板子总数"
            ),
        ),
        migrations.AlterField(
            model_name="historicaloffload",
            name="public_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la,sav公仓拆柜板子总数"
            ),
        ),
        migrations.AlterField(
            model_name="offload",
            name="other_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la,sav私仓拆柜板子总数"
            ),
        ),
        migrations.AlterField(
            model_name="offload",
            name="public_total_pallet",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="la,sav公仓拆柜板子总数"
            ),
        ),
    ]
