# Generated by Django 4.2.7 on 2026-05-20 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0337_alter_historicaloffload_other_total_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
        migrations.CreateModel(
            name='HistoricalShipmentBindingLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bind', '绑定约'), ('unbind', '解绑约')], max_length=20, verbose_name='操作类型')),
                ('po_type', models.CharField(choices=[('pallet', 'Pallet'), ('packing_list', 'PackingList')], max_length=20, verbose_name='PO类型')),
                ('po_id', models.IntegerField(verbose_name='PO ID')),
                ('po_display', models.CharField(blank=True, max_length=500, null=True, verbose_name='PO显示信息')),
                ('shipment_batch_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipment批次号')),
                ('delivery_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库类型')),
                ('container_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='柜号')),
                ('destination', models.CharField(blank=True, max_length=4000, null=True, verbose_name='仓点')),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='仓库')),
                ('operator_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='操作人用户名')),
                ('operation_button', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作按钮名称')),
                ('operation_time_utc', models.DateTimeField(blank=True, editable=False, verbose_name='操作时间(UTC)')),
                ('operation_time_beijing', models.DateTimeField(verbose_name='操作时间(北京时间)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'historical shipment binding log',
                'verbose_name_plural': 'historical shipment binding logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShipmentBindingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bind', '绑定约'), ('unbind', '解绑约')], max_length=20, verbose_name='操作类型')),
                ('po_type', models.CharField(choices=[('pallet', 'Pallet'), ('packing_list', 'PackingList')], max_length=20, verbose_name='PO类型')),
                ('po_id', models.IntegerField(verbose_name='PO ID')),
                ('po_display', models.CharField(blank=True, max_length=500, null=True, verbose_name='PO显示信息')),
                ('shipment_batch_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipment批次号')),
                ('delivery_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库类型')),
                ('container_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='柜号')),
                ('destination', models.CharField(blank=True, max_length=4000, null=True, verbose_name='仓点')),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='仓库')),
                ('operator_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='操作人用户名')),
                ('operation_button', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作按钮名称')),
                ('operation_time_utc', models.DateTimeField(auto_now_add=True, verbose_name='操作时间(UTC)')),
                ('operation_time_beijing', models.DateTimeField(verbose_name='操作时间(北京时间)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_binding_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'db_table': 'warehouse_shipment_binding_log',
                'ordering': ['-operation_time_utc'],
                'indexes': [models.Index(fields=['po_type', 'po_id'], name='warehouse_s_po_type_5a88f5_idx'), models.Index(fields=['operation_time_utc'], name='warehouse_s_operati_bba69a_idx'), models.Index(fields=['operator'], name='warehouse_s_operato_a96e58_idx'), models.Index(fields=['delivery_type'], name='warehouse_s_deliver_26b03e_idx'), models.Index(fields=['container_number'], name='warehouse_s_contain_dc1db9_idx')],
            },
        ),
    ]
