# Generated by Django 5.1.1 on 2026-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0338_fleet_delivery_type_historicalfleet_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipmentbindinglog',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('master', '主约'), ('actual', '实际约')], max_length=20, null=True, verbose_name='约类型'),
        ),
        migrations.AddField(
            model_name='shipmentbindinglog',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('master', '主约'), ('actual', '实际约')], max_length=20, null=True, verbose_name='约类型'),
        ),
    ]
