# Generated by Django 4.2.7 on 2026-05-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0339_historicalshipmentbindinglog_shipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipmentbindinglog',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('master', '主约'), ('actual', '实际约'), ('all', '俩约')], max_length=20, null=True, verbose_name='约类型'),
        ),
        migrations.AlterField(
            model_name='shipmentbindinglog',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('master', '主约'), ('actual', '实际约'), ('all', '俩约')], max_length=20, null=True, verbose_name='约类型'),
        ),
    ]
