# Generated by Django 4.2.7 on 2026-05-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0340_alter_historicalshipmentbindinglog_shipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipmentbindinglog',
            name='po_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PO_ID'),
        ),
        migrations.AlterField(
            model_name='shipmentbindinglog',
            name='po_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PO_ID'),
        ),
    ]
