# Generated by Django 4.2.7 on 2026-05-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0341_alter_historicalshipmentbindinglog_po_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpallet",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="拆柜时间"),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="released_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="记录卡板状态变成可派送的时间,解除暂扣时间",
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="拆柜时间"),
        ),
        migrations.AddField(
            model_name="pallet",
            name="released_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="记录卡板状态变成可派送的时间,解除暂扣时间",
            ),
        ),
    ]
