# Generated by Django 4.2.7 on 2026-05-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0342_historicalpallet_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpallet",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpallet",
            name="priority",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpallet",
            name="slot",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpallet",
            name="zipcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="PO_ID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="priority",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="slot",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="zipcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
