# Generated by Django 4.2.7 on 2026-06-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0343_alter_historicalpallet_po_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipment',
            name='load_type',
            field=models.CharField(blank=True, choices=[('卡板', '卡板'), ('地板', '地板')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='load_type',
            field=models.CharField(blank=True, choices=[('卡板', '卡板'), ('地板', '地板')], max_length=255, null=True),
        ),
    ]
