# Generated by Django 4.2.7 on 2026-06-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0343_alter_historicalpallet_po_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoicestatusv2",
            name="preport_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "未录入"),
                    ("in_progress", "录入中"),
                    ("save", "暂存"),
                    ("pending_review", "待组长审核"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                ],
                default="unstarted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoicestatusv2",
            name="preport_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "未录入"),
                    ("in_progress", "录入中"),
                    ("save", "暂存"),
                    ("pending_review", "待组长审核"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                ],
                default="unstarted",
                max_length=20,
            ),
        ),
    ]
