# Generated by Django 4.2.7 on 2026-06-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0344_alter_historicalinvoicestatusv2_preport_status_and_more"),
        ("warehouse", "0345_systemparameter_historicalsystemparameter"),
    ]

    operations = []
