# Generated by Django 5.1.1 on 2026-06-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0346_merge_20260601_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemparameter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalsystemparameter',
            name='value',
            field=models.TextField(verbose_name='参数值'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='value',
            field=models.TextField(verbose_name='参数值'),
        ),
        migrations.AlterUniqueTogether(
            name='systemparameter',
            unique_together={('category', 'key', 'value')},
        ),
    ]
