# Generated by Django 4.2.7 on 2026-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0347_system_parameter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemparameter',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='供应商图片'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carrier_logos/', verbose_name='供应商图片'),
        ),
    ]
