# Generated by Django 4.2.7 on 2026-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0348_historicalsystemparameter_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsystemparameter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='systemparameter',
            name='image',
        ),
        migrations.AddField(
            model_name='historicalsystemparameter',
            name='image_base64',
            field=models.TextField(blank=True, default='', verbose_name='供应商图片Base64'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='image_base64',
            field=models.TextField(blank=True, default='', verbose_name='供应商图片Base64'),
        ),
    ]
