# Generated by Django 4.2.7 on 2026-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0349_alter_historicalinvoicev2_receivable_wh_other_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_wh_other_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内私仓费用"
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_wh_public_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内公仓费用"
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_wh_other_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内私仓费用"
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_wh_public_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内公仓费用"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicev2",
            name="receivable_wh_other_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoicev2",
            name="receivable_wh_public_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoicev2",
            name="receivable_wh_other_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoicev2",
            name="receivable_wh_public_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
