# Generated by Django 4.2.7 on 2026-06-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0349_remove_historicalsystemparameter_image_and_more"),
        ("warehouse", "0350_historicalinvoicev2_payable_wh_other_amount_and_more"),
    ]

    operations = []
