# Generated by Django 4.2.7 on 2026-06-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0351_merge_20260603_1735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoiceitemv2",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("receivable", "应收账单"),
                    ("payable", "应付账单"),
                    ("payable_direct", "应付直送账单"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicestatusv2",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("receivable", "应收账单"),
                    ("payable", "应付账单"),
                    ("payable_direct", "应付直送账单"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicestatusv2",
            name="warehouse_other_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "未录入"),
                    ("in_progress", "录入中"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                    ("financials_completed", "财务已完成"),
                ],
                default="unstarted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicestatusv2",
            name="warehouse_public_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "未录入"),
                    ("in_progress", "录入中"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                    ("financials_completed", "财务已完成"),
                ],
                default="unstarted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemv2",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("receivable", "应收账单"),
                    ("payable", "应付账单"),
                    ("payable_direct", "应付直送账单"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoicestatusv2",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("receivable", "应收账单"),
                    ("payable", "应付账单"),
                    ("payable_direct", "应付直送账单"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoicestatusv2",
            name="warehouse_other_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "未录入"),
                    ("in_progress", "录入中"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                    ("financials_completed", "财务已完成"),
                ],
                default="unstarted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoicestatusv2",
            name="warehouse_public_status",
            field=models.CharField(
                choices=[
                    ("unstarted", "未录入"),
                    ("in_progress", "录入中"),
                    ("completed", "已完成"),
                    ("rejected", "已驳回"),
                    ("financials_completed", "财务已完成"),
                ],
                default="unstarted",
                max_length=20,
            ),
        ),
    ]
