# Generated by Django 4.2.7 on 2026-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0352_alter_historicalinvoiceitemv2_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipmentbindinglog',
            name='shipping_mark',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='唛头'),
        ),
        migrations.AddField(
            model_name='shipmentbindinglog',
            name='shipping_mark',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='唛头'),
        ),
    ]
