# Generated by Django 4.2.7 on 2026-06-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0353_historicalshipmentbindinglog_shipping_mark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_warehouse_amount_pending_verification",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内待核销金额"
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoicev2",
            name="payable_warehouse_amount_written_off",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内已核销金额"
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_warehouse_amount_pending_verification",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内待核销金额"
            ),
        ),
        migrations.AddField(
            model_name="invoicev2",
            name="payable_warehouse_amount_written_off",
            field=models.FloatField(
                blank=True, null=True, verbose_name="应付库内已核销金额"
            ),
        ),
    ]
