# Generated by Django 4.2.7 on 2026-06-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0355_containerpickupcarrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='delivery_est_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='delivery_est_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='notify_cus_del_time',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='delivery_est_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='delivery_est_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='notify_cus_del_time',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='delivery_est_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='delivery_est_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='notify_cus_del_time',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='delivery_est_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='delivery_est_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='notify_cus_del_time',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
