# Generated by Django 4.2.7 on 2026-06-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0356_historicalpackinglist_delivery_est_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoiceitemv2',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
