# Generated by Django 4.2.7 on 2026-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0357_alter_historicalinvoiceitemv2_po_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetshipmentpallet',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfleetshipmentpallet',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpalletdestroyed',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='palletdestroyed',
            name='PO_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
