# Generated by Django 4.2.7 on 2026-06-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0358_alter_fleetshipmentpallet_po_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpackinglist",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="historicalpackinglist",
            name="dropshipping_item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物名称"
            ),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="dropshipping_item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物名称"
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="dropshipping_item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物名称"
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="dropshipping_item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物名称"
            ),
        ),
    ]
