# Generated by Django 4.2.7 on 2026-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0359_historicalpackinglist_dropshipping_item_model_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipment',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓'), ('dropshipping', '一件代发')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓'), ('dropshipping', '一件代发')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
    ]
