# Generated by Django 4.2.7 on 2026-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0360_alter_historicalshipment_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓'), ('dropshipping', '一件代发')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('public', '公仓'), ('other', '私仓'), ('dropshipping', '一件代发')], max_length=255, null=True, verbose_name='仓库类型'),
        ),
    ]
