# Generated by Django 4.2.7 on 2026-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0361_alter_fleet_delivery_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="historicalabnormaloffloadstatus",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
    ]
