# Generated by Django 4.2.7 on 2026-06-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0362_abnormaloffloadstatus_dropshipping_item_model_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpalletdestroyed",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="historicalpalletdestroyed",
            name="dropshipping_item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物名称"
            ),
        ),
        migrations.AddField(
            model_name="palletdestroyed",
            name="dropshipping_item_model_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物型号"
            ),
        ),
        migrations.AddField(
            model_name="palletdestroyed",
            name="dropshipping_item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="一件代发货物名称"
            ),
        ),
    ]
