# Generated by Django 4.2.7 on 2026-07-10 07:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0363_historicalpalletdestroyed_dropshipping_item_model_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshipCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_mark', models.CharField(db_index=True, max_length=255, verbose_name='唛头')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='型号')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称')),
                ('pcs', models.PositiveIntegerField(default=0, verbose_name='当前库存件数')),
                ('pallets', models.PositiveIntegerField(default=0, verbose_name='当前板数')),
                ('unit_weight_lbs', models.FloatField(blank=True, null=True)),
                ('total_weight_lbs', models.FloatField(null=True)),
                ('total_weight_kg', models.FloatField(null=True)),
                ('cbm', models.FloatField(null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='长')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='宽')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)], verbose_name='高')),
                ('PO_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('shipped_quantity', models.PositiveIntegerField(default=0, verbose_name='累计出库件数')),
                ('returned_quantity', models.PositiveIntegerField(default=0, verbose_name='累计退货件数')),
                ('delivery_type', models.CharField(choices=[('pickup', '自提'), ('self_ship', '自发')], default='pickup', max_length=20, verbose_name='提货类型')),
                ('address', models.TextField(blank=True, null=True, verbose_name='提货地址')),
                ('status', models.CharField(choices=[('not_in_stock', '未入库'), ('in_stock', '在库'), ('all_out', '全部出库')], default='in_stock', max_length=20, verbose_name='货物状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.container', verbose_name='柜子')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.order', verbose_name='关联订单')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.zemwarehouse', verbose_name='所在仓库')),
            ],
        ),
        migrations.CreateModel(
            name='DropshipShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_batch_number', models.CharField(max_length=255, unique=True, verbose_name='预约批次号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expected_shipped_date', models.DateField(blank=True, null=True, verbose_name='预计出库日期')),
                ('expected_delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('total_pcs', models.PositiveIntegerField(default=0, verbose_name='总出库件数')),
                ('total_pallets', models.PositiveIntegerField(default=0, verbose_name='总板数')),
                ('pod_file', models.FileField(blank=True, null=True, upload_to='pod_files/', verbose_name='POD文件')),
                ('pod_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='POD上传时间')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.zemwarehouse', verbose_name='出库仓库')),
            ],
        ),
        migrations.CreateModel(
            name='DropshipShipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.PositiveIntegerField(verbose_name='出库件数（件）')),
                ('pallets', models.PositiveIntegerField(default=0, verbose_name='板数')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dropshipcargo', verbose_name='货物')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='warehouse.dropshipshipment', verbose_name='预约批次')),
            ],
        ),
        migrations.CreateModel(
            name='DropshipInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('unpack', '拆柜入库'), ('return', '退货入库'), ('transfer', '调拨入库'), ('pick', '预约出库'), ('adjust', '库存调整')], max_length=20, verbose_name='操作类型')),
                ('pcs_change', models.IntegerField(verbose_name='件数变动（正=增加，负=减少）')),
                ('after_pcs', models.PositiveIntegerField(verbose_name='操作后件数')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作人')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_verify', models.BooleanField(default=False, verbose_name='是否核验')),
                ('verify_pcs', models.PositiveIntegerField(verbose_name='操作后件数')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dropshipcargo', verbose_name='货物')),
                ('shipment_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.dropshipshipmentdetail', verbose_name='关联出库明细')),
            ],
        ),
        migrations.AddIndex(
            model_name='dropshipshipmentdetail',
            index=models.Index(fields=['shipment'], name='warehouse_d_shipmen_7309ce_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipshipmentdetail',
            index=models.Index(fields=['cargo'], name='warehouse_d_cargo_i_f049d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dropshipshipmentdetail',
            unique_together={('shipment', 'cargo')},
        ),
        migrations.AddIndex(
            model_name='dropshipshipment',
            index=models.Index(fields=['shipment_batch_number'], name='warehouse_d_shipmen_26b792_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipinventory',
            index=models.Index(fields=['cargo', 'transaction_type'], name='warehouse_d_cargo_i_550048_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipinventory',
            index=models.Index(fields=['transaction_date'], name='warehouse_d_transac_fff1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipinventory',
            index=models.Index(fields=['cargo', 'transaction_date'], name='warehouse_d_cargo_i_63340f_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipcargo',
            index=models.Index(fields=['shipping_mark'], name='warehouse_d_shippin_040290_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipcargo',
            index=models.Index(fields=['order', 'shipping_mark'], name='warehouse_d_order_i_ea772c_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipcargo',
            index=models.Index(fields=['status'], name='warehouse_d_status_ea59e0_idx'),
        ),
        migrations.AddIndex(
            model_name='dropshipcargo',
            index=models.Index(fields=['container'], name='warehouse_d_contain_f9bc0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dropshipcargo',
            unique_together={('shipping_mark', 'order')},
        ),
    ]
