# Generated by Django 4.2.7 on 2026-07-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0364_dropshipcargo_dropshipshipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='hasOtherFile',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ltl是否需要下载其他文件'),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='needLabel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ltl是否需要下载label文件'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='hasOtherFile',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ltl是否需要下载其他文件'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='needLabel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ltl是否需要下载label文件'),
        ),
    ]
