# Generated by Django 4.2.7 on 2026-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0365_historicalshipment_hasotherfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='ltl_other_file_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ltl_other_file_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='delivery_type',
            field=models.CharField(choices=[('mixed', '混合'), ('public', '公仓'), ('other', '其他'), ('dropship', '一件代发')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='delivery_type',
            field=models.CharField(choices=[('mixed', '混合'), ('public', '公仓'), ('other', '其他'), ('dropship', '一件代发')], default='mixed', max_length=20),
        ),
    ]
