# Generated by Django 4.2.7 on 2026-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0366_historicalshipment_ltl_other_file_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropshipcargo",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "自提"), ("self_ship", "自发")],
                default="pickup",
                max_length=20,
                verbose_name="派送方式",
            ),
        ),
        migrations.AlterField(
            model_name="dropshipcargo",
            name="delivery_type",
            field=models.CharField(
                default="一件代发", max_length=20, verbose_name="提货类型"
            ),
        ),
    ]
