# Generated by Django 4.2.7 on 2026-07-13 07:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0367_dropshipcargo_delivery_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDropshipCargo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "shipping_mark",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="唛头"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="型号"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="产品名称"
                    ),
                ),
                (
                    "pcs",
                    models.PositiveIntegerField(default=0, verbose_name="当前库存件数"),
                ),
                (
                    "pallets",
                    models.PositiveIntegerField(default=0, verbose_name="当前板数"),
                ),
                ("unit_weight_lbs", models.FloatField(blank=True, null=True)),
                ("total_weight_lbs", models.FloatField(null=True)),
                ("total_weight_kg", models.FloatField(null=True)),
                ("cbm", models.FloatField(null=True)),
                (
                    "long",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=10
                            ),
                        ],
                        verbose_name="长",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=10
                            ),
                        ],
                        verbose_name="宽",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.DecimalValidator(
                                decimal_places=2, max_digits=10
                            ),
                        ],
                        verbose_name="高",
                    ),
                ),
                ("PO_ID", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "shipped_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="累计出库件数"),
                ),
                (
                    "returned_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="累计退货件数"),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        default="一件代发", max_length=20, verbose_name="提货类型"
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("pickup", "自提"), ("self_ship", "自发")],
                        default="pickup",
                        max_length=20,
                        verbose_name="派送方式",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="提货地址"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_in_stock", "未入库"),
                            ("in_stock", "在库"),
                            ("all_out", "全部出库"),
                        ],
                        default="in_stock",
                        max_length=20,
                        verbose_name="货物状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehouse.container",
                        verbose_name="柜子",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehouse.order",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="warehouse.zemwarehouse",
                        verbose_name="所在仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical dropship cargo",
                "verbose_name_plural": "historical dropship cargos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
