# Generated by Django 4.2.7 on 2026-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0368_historicaldropshipcargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpallet",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="型号"
            ),
        ),
        migrations.AddField(
            model_name="historicalpallet",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="产品名称"
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="型号"
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="产品名称"
            ),
        ),
    ]
