# Generated by Django 4.2.7 on 2026-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0369_historicalpallet_model_historicalpallet_product_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="abnormaloffloadstatus",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="型号"
            ),
        ),
        migrations.AddField(
            model_name="historicalabnormaloffloadstatus",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="型号"
            ),
        ),
    ]
