# Generated by Django 4.2.7 on 2026-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0370_abnormaloffloadstatus_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropshipcargo",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_in_stock", "未入库"),
                    ("in_stock", "在库"),
                    ("all_out", "全部出库"),
                ],
                default="not_in_stock",
                max_length=20,
                verbose_name="货物状态",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldropshipcargo",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_in_stock", "未入库"),
                    ("in_stock", "在库"),
                    ("all_out", "全部出库"),
                ],
                default="not_in_stock",
                max_length=20,
                verbose_name="货物状态",
            ),
        ),
    ]
