# Generated by Django 4.2.7 on 2026-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0371_alter_dropshipcargo_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropshipinventory",
            name="after_pcs",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="操作后件数"
            ),
        ),
    ]
