# Generated by Django 4.2.7 on 2026-07-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0372_alter_dropshipinventory_after_pcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipshipment',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='dropshipshipment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='dropshipshipment',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='收货地址'),
        ),
    ]
