# Generated by Django 4.2.7 on 2026-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0373_alter_dropshipshipment_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipinventory',
            name='verify_pcs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='核验后件数'),
        ),
    ]
