# Generated by Django 4.2.7 on 2026-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0374_alter_dropshipinventory_verify_pcs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropshipshipment',
            old_name='expected_delivered_date',
            new_name='arrived_at',
        ),
        migrations.RemoveField(
            model_name='dropshipshipment',
            name='expected_shipped_date',
        ),
        migrations.AddField(
            model_name='dropshipshipment',
            name='picku_time',
            field=models.DateField(blank=True, null=True, verbose_name='预计提货日期'),
        ),
        migrations.AddField(
            model_name='dropshipshipment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际出库日期'),
        ),
    ]
