# Generated by Django 4.2.7 on 2026-07-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0375_rename_expected_delivered_date_dropshipshipment_arrived_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropshipshipment',
            old_name='picku_time',
            new_name='pickup_time',
        ),
    ]
