# Generated by Django 4.2.7 on 2026-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0376_rename_picku_time_dropshipshipment_pickup_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshipshipment',
            name='total_pallets',
        ),
        migrations.AddField(
            model_name='dropshipinventory',
            name='verfiy_pcs_change',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际件数变动（正=增加，负=减少）'),
        ),
        migrations.AlterField(
            model_name='dropshipinventory',
            name='pcs_change',
            field=models.IntegerField(blank=True, null=True, verbose_name='预计件数变动（正=增加，负=减少）'),
        ),
    ]
