# Generated by Django 4.2.7 on 2026-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0377_remove_dropshipshipment_total_pallets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshipshipment',
            name='pod_file',
        ),
        migrations.AddField(
            model_name='dropshipshipment',
            name='pod_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
