# Generated by Django 5.1.1 on 2026-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0378_remove_dropshipshipment_pod_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipshipmentdetail',
            name='returned_pcs',
            field=models.PositiveIntegerField(default=0, verbose_name='已退货件数'),
        ),
    ]
