# Generated by Django 5.1.1 on 2026-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0379_add_returned_pcs_to_shipment_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmaster',
            name='is_dropship',
            field=models.BooleanField(default=False, verbose_name='是否一件代发'),
        ),
    ]
