# Generated by Django 5.1.1 on 2026-07-27 08:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0380_add_is_dropship_to_quotation_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDropshipInventory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('unpack', '拆柜入库'), ('return', '退货入库'), ('transfer', '调拨入库'), ('pick', '预约出库'), ('adjust', '库存调整')], max_length=20, verbose_name='操作类型')),
                ('pcs_change', models.IntegerField(blank=True, null=True, verbose_name='预计件数变动（正=增加，负=减少）')),
                ('after_pcs', models.PositiveIntegerField(blank=True, null=True, verbose_name='操作后件数')),
                ('transaction_date', models.DateTimeField(blank=True, editable=False, verbose_name='操作时间')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作人')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_verify', models.BooleanField(default=False, verbose_name='是否核验')),
                ('verfiy_pcs_change', models.IntegerField(blank=True, null=True, verbose_name='实际件数变动（正=增加，负=减少）')),
                ('verify_pcs', models.PositiveIntegerField(blank=True, null=True, verbose_name='核验后件数')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.dropshipcargo', verbose_name='货物')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment_detail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.dropshipshipmentdetail', verbose_name='关联出库明细')),
            ],
            options={
                'verbose_name': 'historical dropship inventory',
                'verbose_name_plural': 'historical dropship inventorys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDropshipShipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('shipment_batch_number', models.CharField(db_index=True, max_length=255, verbose_name='预约批次号')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('pickup_time', models.DateField(blank=True, null=True, verbose_name='预计提货日期')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='实际出库日期')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('total_pcs', models.PositiveIntegerField(default=0, verbose_name='总出库件数')),
                ('pod_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('pod_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='POD上传时间')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='收货地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.zemwarehouse', verbose_name='出库仓库')),
            ],
            options={
                'verbose_name': 'historical dropship shipment',
                'verbose_name_plural': 'historical dropship shipments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDropshipShipmentDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pcs', models.PositiveIntegerField(verbose_name='出库件数（件）')),
                ('returned_pcs', models.PositiveIntegerField(default=0, verbose_name='已退货件数')),
                ('pallets', models.PositiveIntegerField(default=0, verbose_name='板数')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.dropshipcargo', verbose_name='货物')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.dropshipshipment', verbose_name='预约批次')),
            ],
            options={
                'verbose_name': 'historical dropship shipment detail',
                'verbose_name_plural': 'historical dropship shipment details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
