# Generated by Django 5.1.1 on 2026-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0381_add_dropship_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipshipment',
            name='status',
            field=models.CharField(choices=[('pending', '已预约'), ('shipped', '已出库'), ('completed', '已完结'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='historicaldropshipshipment',
            name='status',
            field=models.CharField(choices=[('pending', '已预约'), ('shipped', '已出库'), ('completed', '已完结'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
