# Generated by Django 5.1.1 on 2026-08-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0382_add_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackinglist',
            name='city',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='company',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalpackinglist',
            name='road',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Road'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='city',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='company',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalpallet',
            name='road',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Road'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='city',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='company',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='road',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Road'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='city',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='company',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='road',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Road'),
        ),
    ]
