# Generated by Django 5.1.1 on 2026-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0383_add_company_road_city_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出库时间'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出库时间'),
        ),
    ]
