# Generated by Django 4.2.7 on 2026-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0384_add_shipped_at_to_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='departured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='国内方的出库时间'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='仓库方的出库时间'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='departured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='国内方的出库时间'),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='仓库方的出库时间'),
        ),
    ]
