# Generated by Django 4.2.7 on 2026-08-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0385_alter_fleet_departured_at_alter_fleet_shipped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="fleet_ltl_status",
            field=models.BooleanField(
                default=False,
                help_text="ltl派送成本录入页面判断是否已录入，True=已录入，False=未录入",
                verbose_name="ltl派送成本录入页面判断是否已录入",
            ),
        ),
        migrations.AddField(
            model_name="historicalfleet",
            name="fleet_ltl_status",
            field=models.BooleanField(
                default=False,
                help_text="ltl派送成本录入页面判断是否已录入，True=已录入，False=未录入",
                verbose_name="ltl派送成本录入页面判断是否已录入",
            ),
        ),
    ]
