# Generated by Django 5.1.1 on 2026-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0386_fleet_fleet_ltl_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpallet',
            name='pickup_images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='拣货单图片列表'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='pickup_images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='拣货单图片列表'),
        ),
    ]
