# Generated by Django 5.1.1 on 2026-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0387_add_pickup_images_to_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='pickup_images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='拣货单图片列表'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='拣货单图片列表'),
        ),
    ]
