# Generated by Django 4.2.7 on 2026-08-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0388_add_pickup_images_to_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpallet',
            name='pickup_images',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='pickup_images',
        ),
    ]
