# Generated by Django 4.2.7 on 2026-09-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0392_multi_carrier_quote_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='multicarrierquotehistory',
            name='kakas_request_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='卡卡省询价请求体'),
        ),
    ]
