# Generated by Django 5.1.1 on 2026-09-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0396_auto_quote_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoQuoteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('configuration', models.JSONField(default=dict)),
                ('origin_label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='autoquoteitem',
            name='analysis_version',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='autoquotebatch',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.autoquoteprofile'),
        ),
        migrations.CreateModel(
            name='AutoQuotePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('platform', models.CharField(max_length=20)),
                ('carrier', models.CharField(max_length=200)),
                ('carrier_code', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('service_code', models.CharField(blank=True, max_length=100)),
                ('series_key', models.CharField(db_index=True, max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('currency_assumed', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comparable', models.BooleanField(default=True)),
                ('platform_complete', models.BooleanField(default=False)),
                ('raw', models.JSONField(default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='warehouse.autoquoteitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'row_number'), name='auto_quote_price_row_unique')],
            },
        ),
    ]
